### ISSUE TITLE
Raiden RESTful API

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#10]
*Expose the API of raiden to external clients.*

## General API Spec:

- **Setting up** the initial connection to the raiden network should be possible **manually** (by opening channels and depositing into them from single API methods)
- Additionally we want to provide a **(semi-)automatic setup** to the network from given configuration-parameters 
*(e.g. based on available assets, so that the node takes care of an optimal connectivity to the raiden network by opening and depositing into channels without any additional considerations from the user)*
- API calls and responses should include a specification of the **API-version** (up from v1.0), so that the API is **future-proof**. The app has to include all versions of the API in the future.

- **MvP**: this version of the API needs to provide all neccessary tools to make it possible to build a **Wallet style UI** (issue #285)

## Functionality
add following methods to `raiden-service.RaidenAPI`:

- `query_endpoint(raiden_address)` - for light clients
- `register_endpoint(endpoint, signature)`
- `get_channel_info()` - retrieve the timeout, deposit, etc

let the caller decide if the called method should be executed asynchronous or waiting
(== `gevent.Greenlet.wait()`)

- `asset_swap(..., wait=<bool>)`
- `expect_asset_swap(..., wait=<bool>)`
- `transfer(..., wait=<bool>)`

The asynchronous method should be the default option,
but when calling via REST the waiting method should be default. 
That's because in e.g. JavaScript one can work easily with Promises.

## Protocol:

- Endpoints of all methods in the `raiden_service.RaidenAPI` are accessible through http-requests and are structured complying to a **RESTful**-pattern. Resources are kept minimal:
     - (e.g. on `/api/channel`
     -`GET` - get channel info,
     -`POST` - open channel,
     -`DELETE` - close channel,
      -`UPDATE` - deposit to channel )
- All http-requests (*-> client-initiated*) are *'blocking'* and at least include information about the **success of the call** in their response message. That way we don't have to work with callback-ids on the client side (see #280 ) but rather can work with promises.
- For **non-client initiated** actions (e.g. incoming transfers, opened channels, channel closing etc.) there will be the **emission of events** from the node to the client
- **Filtering** of the events will be done **on the client side**, so all events will be put in a FIFO-queue and sequentially forwarded to the client
- We assume that **only 1 client per node** is connected
- Events and responses will be **serialized to JSON**, 'difficult' data encoding will be reused from the Ethereum protocol (pyethapp/pyethereum) where possible
    (e.g. hex encoding for addresses)

## Transport:

- Method-calls: **TCP** (http-requests)
- Events:   the client can choose between
    1) TCP (**polling** http-requests)
    2) TCP ( **long-polling**; *'fake' push notifications*)

- The **interface** for the API has to be **uniform**, independent of the chosen transport-layer

## Tasklist

- [x] [Expose blockchain events in the REST api](https://github.com/raiden-network/raiden/issues/467)
- [x] [Add http endpoint for exchange task](https://github.com/raiden-network/raiden/issues/465)
- [x] [Expose Raiden Rest API at Raiden start](https://github.com/raiden-network/raiden/issues/464) 
- [ ] [Expose Raiden internal events from the REST API](https://github.com/raiden-network/raiden/issues/466) --> #594  #466 
- [x] [Add rpc endpoints for `connect` and `leave` of token networks](https://github.com/raiden-network/raiden/issues/508)

**Comment by konradkonrad** [comment]
> Expose the Raiden API

to whom?

**Comment by heikoheiko** [comment]
to users from localhost for now

**Comment by heikoheiko** [comment]
@ezdac can you comment and optionally close the issue?

**Comment by ezdac** [comment]
`open_channel()` and `close_channel()` still need to be implemented.
In general - it would be a good idea to use the WAMP protocol since it already includes json-rpc calls and the pubsubs, required in the webui.
BUT i don't feel very confident to use the gevent-websocket for anything else than the proof of concept-webui.
Development for the package seems to be halted and WAMP v2 isn't supported atm.

**Comment by heikoheiko** [comment]
can you check if autobahn|Python supports v2? 
http://autobahn.ws/python/index.html

**Comment by ezdac** [comment]
it does, but it uses asyncio (py3) // Twisted instead of gevent

**Comment by heikoheiko** [comment]
i know. but we could use py3 (even pypy3) and asyncio too.

**Comment by heikoheiko** [comment]
after all we are talking about a few lines of code here, so it's not too important that it's future proof.

**Comment by LefterisJP** [comment]
@konradkonrad: Is the current status of the Raiden Network API good enough for this issue to be considered complete? If so let's close this.

**Comment by konradkonrad** [comment]
To my knowledge there is no ~stable implementation of an RPC-Api. 

So the python API seems to be sufficient, the RPC-Api would probably need to be cherry-picked from the IoT-Demo branch. @ezdac any input on this?

**Comment by konradkonrad** [comment]
In light of the MVP this ticket should be revised to better specify the API we want to expose to users.

**Comment by ezdac** [comment]
I'm currently reworking the API-exposure based on the recent experiments with `gevent-websocket`.
The idea is to support 3 communication-procedures, all of which are transported over a single websocket and comply with JSON-RPC-standards:
-  **standard JSON-RPC calls for synchronous methods** that don't rely on callback execution and success-confirmations: the result of the call is directly returned to the websocket.
- **JSON-RPC calls for asynchronous methods** relying on callback execution:
the call itself triggers a method like `transfer_async()` with given arguments.
Internally, a `call_id` is constructed and a callback-function is bound to the `call_id`.
The RPC then returns the `call_id` to the websocket, making it possible to wait for the callback to execute on the client side. The callback will post a success/timeout message (or any other arbitrary information) to the websocket, where the client can process this.

- **push Events** - this probably is the most difficult part, so for now a simplified version of this is planned:
Different getter methods will be implemented in the API,  e.g. `get_balance()` that automatically get triggered when a balance update is deducted in raiden. So for every update the client receives the return value of the getter over the websocket, implying that balance-updates have to be considered. In order to trigger the update, something like `gevent.Event()`'s are needed down the raiden codebase on every relevant state-change.

One part to consider is also that the protocol and messages are non-standard and have to be defined and documented. For easier adaption we should also consider something like a `raiden.js`-client that offers a high-level interface with the raiden-api and handles the event-updates with something like `ReactiveX.js`'s Observables etc.

**Comment by ezdac** [comment]
*Expose the API of raiden to external clients.*


## General API Spec:

- **Setting up** the initial connection to the raiden network should be possible **manually** (by opening channels and depositing into them from single API methods)
- Additionally we want to provide a **(semi-)automatic setup** to the network from given configuration-parameters 
*(e.g. based on available assets, so that the node takes care of an optimal connectivity to the raiden network by opening and depositing into channels without any additional considerations from the user)*
- API calls and responses should include a specification of the **API-version** (up from v1.0), so that the API is **future-proof**. The app has to include all versions of the API in the future.

- **MvP**: this version of the API needs to provide all neccessary tools to make it possible to build a **Wallet style UI** (issue #285)

## Protocol:

- Endpoints of all methods in the `raiden_service.RaidenAPI` are accessible through http-requests and are structured complying to a **RESTful**-pattern. Resources are kept minimal:
     - (e.g. on `/api/channel`
     -`GET` - get channel info,
     -`POST` - open channel,
     -`DELETE` - close channel,
      -`UPDATE` - deposit to channel )
- All http-requests (*-> client-initiated*) are *'blocking'* and at least include information about the **success of the call** in their response message. That way we don't have to work with callback-ids on the client side (see #280 ) but rather can work with promises.
- For **non-client initiated** actions (e.g. incoming transfers, opened channels, channel closing etc.) there will be the **emission of events** from the node to the client
- **Filtering** of the events will be done **on the client side**, so all events will be put in a FIFO-queue and sequentially forwarded to the client
- We assume that **only 1 client per node** is connected
- Events and responses will be **serialized to JSON**, 'difficult' data encoding will be reused from the Ethereum protocol (pyethapp/pyethereum) where possible
    (e.g. hex encoding for addresses)


## Transport:

- Method-calls: **TCP** (http-requests)
- Events:   the client can choose between
    1) TCP (**polling** http-requests)
    2) TCP ( **long-polling**; *'fake' push notifications*)

- The **interface** for the API has to be **uniform**, independent of the chosen transport-layer


## Further outlook:
### This is not part of this MvP!

- Calls and true push-events over **web-socket** connection(s)
- **Filtering** inside the node:
    - step 1) the client registers filters with a method call
    - step 2) either the client polls for filter changes
                    or the client listens for events pushed by the node

**Comment by ezdac** [comment]
updated issue description 'Functionality' to include `asset_swap`, `expect_asset_swap` and `transfer` methods with additional `wait` argument for asynchronous/waiting behaviour.

**Comment by hackaugusto** [comment]
Regarding the URL naming, IMO we should expose collections instead of items, so, instead of `/api/channel` we should use `/api/channels`.

**Comment by LefterisJP** [comment]
Should not have been closed yet :)

**Comment by LefterisJP** [comment]
This task is almost finished.

Remaining issues to be done in order for the API to be considered complete are:

- [ ] [Expose blockchain events in the REST api](https://github.com/raiden-network/raiden/issues/467)
- [ ] [Add http endpoint for exchange task](https://github.com/raiden-network/raiden/issues/465)
- [ ] [Expose Raiden Rest API at Raiden start](https://github.com/raiden-network/raiden/issues/464)
- [ ] [Expose Raiden internal events from the REST API](https://github.com/raiden-network/raiden/issues/466)

**Comment by LefterisJP** [comment]
This task as originally defined is now finished. We will probably do more changes in the API but we now do have a Rest API available. So this Meta task no longer serves any purpose.
