### ISSUE TITLE
Provide homebrew tap for binary mac releases

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1243]
## Problem Definition

Now that the binary mac build is automatically produced it would be beneficial to also provide a homebrew tap to ease installation and update for homebrew users.

## Task list
- [x] Create [brew tap repository](https://docs.brew.sh/Taps.html) (i.e. `raiden-network/homebrew-raiden`)
- [ ] Update Travis CI configuration to update brew formula on new releases
- [ ] Mention in install / usage docs
- [ ] Add to change log

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.2 ETH (116.9 USD @ $584.51/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/raiden-network/raiden/1243/561).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $13,682.43 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@cpurta](https://gitcoin.co/profile/cpurta) 

 has committed to working on this project to be completed 4 weeks, 1 day from now.


@vs77bb, __please see the below comments / questions regarding approach for this ticket from the bounty hunter(s):__ 
- [@cpurta](https://gitcoin.co/profile/cpurta): This looks like a great issue to knock out. Would like to take this on, I believe that I can get this completed within a few days.

**Comment by gitcoinbot** [comment]
@cpurta Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=1) | [3 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=3) | [5 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=5) | [10 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=10) | [100 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=100)

**Comment by cpurta** [comment]
@ulope I have a WIP PR open to address 3,4 of the task list and left a comment about a fork to address 1. Once the repo is made it should be straight-forward to work on 2 and wrap this up.

**Comment by ulope** [comment]
@cpurta thanks a lot for taking this on!

We've created the [homebrew-raiden](https://github.com/raiden-network/homebrew-raiden) repo now. Can you please fork it and open a PR with your code?

**Comment by gitcoinbot** [comment]
@cpurta Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=1) | [3 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=3) | [5 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=5) | [10 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=10) | [100 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=100)

**Comment by cpurta** [comment]
Still working on this issue, PR open in raiden-network/homebrew-raiden.

**Comment by ulope** [comment]
@cpurta Thanks, I've approved and merged raiden-network/homebrew-raiden#2. 
That means from the tasks listed above only the automated updating of the formula remains.

**Comment by vs77bb** [comment]
@ulope @cpurta great progress! I'll be on the lookout for the automated formula updating PR and will pay out upon merge 👍

**Comment by gitcoinbot** [comment]
@cpurta Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=1) | [3 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=3) | [5 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=5) | [10 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=10) | [100 days](https://gitcoin.co/issue/raiden-network/raiden/1243/561?snooze=100)

**Comment by cpurta** [comment]
@vs77bb This issue has been close out. Would you be able to pay out and close the issue on gitcoin?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 0.2 ETH (87.39 USD @ $436.94/ETH) has been submitted by__:

 1. [@cpurta](https://gitcoin.co/profile/cpurta)



@vs77bb please take a look at the submitted work:
* [PR](https://github.com/raiden-network/raiden/pull/1518) by @cpurta

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/raiden-network/raiden/1243/561)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
$29,048.27 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.2 ETH (96.57 USD @ $482.86/ETH) attached to this issue has been approved & issued to @cpurta.__  

 * Learn more at [on the Gitcoin Issue Details page](https://gitcoin.co/issue/raiden-network/raiden/1243/561)
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $17,805.32 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
