### ISSUE TITLE
Integrate raiden smart contracts from the contracts repo

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1383]
We need to integrate the new contracts from the [smart contracts](https://github.com/raiden-network/raiden-contracts) repository in Raiden client core.

That would entail:

- [x] Adding the repository as a pypi dependency
  - This requires us to remove the `pyethereum` dependency and is quite a long shot (reason is that `eth-tester==0.1.0b24` requires `rlp>1.0`). It will probably be easier to copy over the `ContractManager` in the beginning.
- [x] Smart contract proxy stuff
  - [x] `deposit` (#1539)
  - [x] `closeChannel` , `updateNonClosingBalanceProof`, `settleChannel` - `balance_hash` (#1538 )
  - [x] `unlock` (#1496  )
- [x] Integrating the smart contracts in the code and replacing the old contracts directory
  - [x] Add contract proxies for `TokenNetwork`, `TokenNetworkRegistry`
  - [x] Test the new wrappers, implement the according fixtures. (#1541)
  - [x] Extend the blockchain service to handle the new proxies
  - [x] Add locked amount to the signed messages [here](https://github.com/raiden-network/raiden/blob/master/raiden/messages.py#L210)
  - [x] Fix contract proxy version checks
  - [x] Add filter for new `TokenNetwork`s events from the `TokenNetworkRegistry` (#1542 )
  - [x] Create "fake" proxy for channel (#1549)
  - [x] Switch the number 2 proxies with the old ones and everything "should" work
  - [x] Edit the ContractManager to work with the new contracts
  - [x] Update the Rest API: #1669

**Comment by palango** [comment]
I started with some work on the proxies here: https://github.com/palango/raiden/tree/add_new_contract_proxies
