### ISSUE TITLE
Replace functions from raiden.utils with eth-utils equivalents

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1422]
## Problem Definition

We currently define some helper functions ourselves in the `raiden.utils` module. We should use the ones that are available in `eth-utils` instead.

### ToDo

Any issue can be solved independently

- [x] Replace `raiden.utils.decode_hex()` with `eth_utils.decode_hex()` (Note that the current `decode_hex` handles more input types, so this might require more changes)
- [x] Replace `raiden.utils.encode_hex()` with `eth_utils.encode_hex()` (Note that the current `encode_hex` handles more input types, so this might require more changes) (#1580)
- [x] Replace `raiden.utils.isaddress()` with `eth_utils.is_binary_address()`. (#1513)
- [x] Replace `raiden.utils.address_decoder()` with `eth_utils.to_canonical_address()`.
- [x] Replace `raiden.utils.address_encoder()` with `eth_utils.to_normalized_address()`. (#1527)
- [x] Replace `raiden.utils.quantity_decoder()` with `eth_utils.to_int()`. 
- [ ] Replace `[un]hexlify` with `eth_utils.(en|de)code_hex` wherever possible and ensure hex-encoded strings are kept `0x`-prefixed: See #1654

**Comment by paradisensei** [comment]
@palango I have noticed that `raiden.utils.address_encoder()` and `eth_utils.to_normalized_address()` behave differently upon receiving an empty string as an input argument.

`raiden.utils.address_encoder()` [permits it](https://github.com/raiden-network/raiden/blob/5914517e2665b42f2682f81a8e262a86d3e2ad98/raiden/utils/__init__.py#L118-L119) and returns `0x`.
`eth_utils.to_normalized_address()` [rises error](https://github.com/ethereum/eth-utils/blob/9ffec4ad7df94a4d2c1951b179707b487bbbaf4b/eth_utils/address.py#L77-L82), because it doesn`t consider an empty string to be a valid address.

I am a newbie here, so it`s hard for me to decide whether it is desired behaviour or may break backward compatibility.

**Comment by palango** [comment]
Hi @paradisensei , that's an interesting special case. Do you know if this is used inside the Raiden codebase? Other than deploying contracts I can't imagine this is important.

**Comment by paradisensei** [comment]
@palango personally I don`t think this is important too.

**Comment by palango** [comment]
@paradisensei Cool, just let me know if you run into problems.

**Comment by paradisensei** [comment]
@palango I have one question regarding replacement of `raiden.utils.encode_hex()` with `eth_utils.encode_hex()`.

`eth_utils.encode_hex()` returns 0x prefixed hex whereas `raiden.utils.encode_hex()` returns hex without 0x prefix. So should I add `eth_utils.remove_0x_prefix` to the result of `eth_utils.encode_hex()` or it doesn`t really matter? Asking because I came upon [this test case](https://github.com/raiden-network/raiden/blob/ad98713c83281c09d7276d2478ef76102f28e2cc/raiden/tests/unit/test_accounts.py#L57).

**Comment by palango** [comment]
Yes, we should aim for that. But I'm worried that this becomes to invasive and we should postpone it a bit. Was that the only problematic part of the code @paradisensei ?

**Comment by paradisensei** [comment]
@palango yes, it seems to be so.

**Comment by paradisensei** [comment]
I'm not sure that replacing `[un]hexlify` is in the scope of the current issue because these functions are not from `raiden.utils` module. And maybe it will be better to create a separate issue for this task for the sake of clarity and not to overflow current issue. @palango @andrevmatos what do you think?

**Comment by palango** [comment]
@paradisensei I opened a follow up in #1654 . Thanks for your help on this issue!
