### ISSUE TITLE
Update documentation for install instructions

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#1482]
## Description
Make sure that the [current docs](https://github.com/raiden-network/raiden/blob/master/docs/overview_and_guide.rst) is easy to follow and provides all the information needed to install Raiden is a fresh Linux and macOS environment.

This issue is an ongoing issue that is dependent on changes to project requirements etc., and should not be considered done until a new user can install Raiden in a fresh environment without problems if following the guide.

## Tasks
- [x] Check if instructions and prerequisites are up-to-date and easy to follow on Linux
- [x] Check if instructions and prerequisites are up-to-date and easy to follow on macOS

If anything is unclear or doesn't work in above points:
- [x]  Specify what's not working and fix the documentation accordingly

**Comment by czepluch** [comment]
Done with https://github.com/raiden-network/raiden/pull/1963. Tested on both Linux and macOS to make sure it should be clear for both OS's.
