### ISSUE TITLE
Update "Getting started with Raiden API" guide

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#1485]
## Description

Make sure that the "Getting started with the Raiden API" [guide](https://github.com/raiden-network/raiden/blob/master/docs/api_walkthrough.rst) is up-to-date with the API and try to simplify some of the sentences.

This issue is dependent on https://github.com/raiden-network/raiden/issues/1477 that makes sure that the API docs are up to date.

## Tasks
- [x] Update the API calls according to code changes
- [x] Remove irrelevant parts
- [ ] Convert long complex sentences into shorter simple sentences

**Comment by czepluch** [comment]
A new and simple guide has been created for now with https://github.com/raiden-network/raiden/pull/1556. We should still update the "Getting started with the Raiden API" documentation too, but I think it is nice to have a very easy to follow guide that can get people started doing payments in a very short time.

**Comment by jomuel** [comment]
I will take over this issue since it's been open for a while now, and I have already done part of it (the updates according to api changes) in #1685.

**Comment by czepluch** [comment]
Waiting for review on https://github.com/raiden-network/raiden/pull/2050
Should get one from Jochen today.

**Comment by czepluch** [comment]
Closed with https://github.com/raiden-network/raiden/pull/2050
