### ISSUE TITLE
Update "Raiden web application tutorial"

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#1487]
## Description

The [Raiden web application tutorial](https://raiden-network.readthedocs.io/en/v0.3.0/webui_tutorial.html) should be tested to check if it is still valid and working for Red Eyes. If it still works we can consider to update the screenshots to be more recent. If changes are made to how the web application works, the tutorial must be updated to reflect this.

## Tasks
- [ ] Check if guide is up-to-date
- [ ] Update screenshots to be recent
- [ ] Update guide if it's not up to date anymore

**Comment by LefterisJP** [comment]
I am also assigning this to @kelsos since he is going to be working on the UI anyway.
