### ISSUE TITLE
Refactor secret unlock logic

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1496]
Secret unlock logic has been changed.  Instead of needing to `unlock` each secret, we now have a batch unlock after the channel has been settled.

TODO:

- [x] add the `SecretRegistry` proxy instance to be available inside the `RaidenService` - https://github.com/raiden-network/raiden/issues/1587
- [x] Take SecretRegistry into account in the state machine - https://github.com/raiden-network/raiden/issues/1579
- [x] Add on-chain secret reveal if a secret is about to expire - https://github.com/raiden-network/raiden/issues/1584
- [x] Remove logic for closing the channel if a secret is about to expire - https://github.com/raiden-network/raiden/issues/1617
- [ ] `transfer/mediated_transfer/target.py` - `handle_inittarget` - rethink `safe_to_wait` in this context, as we only have 1 on-chain transaction now. - https://github.com/raiden-network/raiden/issues/1603

2. Add batch unlock state changes and events
- [x] move unlock from `handle_channel_closed` to `handle_channel_settled` in `transfer.channel.py`
- [x] `get_known_unlocks` used now in `handle_channel_settled` should return the packed pending transfers data instead of an array of locks.
- [x] `handle_contract_channelunlock` which handles sending the `unlock` transaction to the contract, now needs to send 1 transaction with the packed data instead of multiple transactions for each lock
- [x] `ContractReceiveChannelUnlock` state change with new data returned by the `ChannelUnlocked`
- [x] handle `ChannelUnlocked` event; it is currently handled by `handle_channel_withdraw` (`blockchain_events_handler.py`). This is a bad name for this functionality. Consider `handle_channel_unlock`. - fixed in https://github.com/raiden-network/raiden/pull/1540
- [ ] limit the number of pending transfers to the gas limit needed to unlock them all - https://github.com/raiden-network/raiden/issues/439  <--- Required only for the mainnet red eyes release

This issue needs more details regarding messages and protocol changes. May need further splitting into issues.

Note:
- for batch unlocking, we can choose between having it as a user-triggered action and doing it automatically after the channel is settled. We are going with the latter, because the first option also needs additional work for adding proper REST APIs & web UI changes.

**Comment by LefterisJP** [comment]
> Consider handle_channel_unlock.

+1. Be explicit in the naming.

**Comment by hackaugusto** [comment]
Parent issue: #1383

**Comment by hackaugusto** [comment]
closing since this is mostly implemented and the two pending bullet points have separate issues, which are not part of the same milestone.
