### ISSUE TITLE
Implement channel withdraw logic for setTotalWithdraw

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1498]
New smart contracts now have token withdraw functionality. 
Note - in the current code, the `withdraw` term is being used by the `unlock` logic. I propose to change reserve this term for the `setTotalWithdraw` related functionality. See https://github.com/raiden-network/raiden/issues/1496 for this.

TODO:

- [ ] add 2 messages: `WithdrawRequest` (for node requesting a withdraw signature from the partner node), `Withdraw` (containing the withdraw signature from the partner node)
- [ ] add corresponding events: `SendWithdrawRequest`, `SendWithdraw`,  `ContractSendChannelWithdraw`
- [ ] add event handlers for the above
- [ ] add corresponding state changes: `ActionWithdraw`, `ReceiveWithdrawRequest`,  `ReceiveWithdraw`,  `ContractReceiveChannelWithdraw` (!note that both Raiden nodes need to process a node's withdraw)
- [ ] Implement new handler for the `ChannelWithdraw` event in `blockchain_events_handler.py`. Proposed name : `handle_channel_(total_)withdraw` 

**Logic sequence diagram**

SC = smart contract on-chain transaction
STC = StateChange
EV = Raiden Event
MSG = Raiden Message

![raidenclientwithdrawlogicsequence2](https://user-images.githubusercontent.com/4785356/40992076-fa019210-68f5-11e8-8943-b77a3074b9b8.png)

Feel free to improve naming.

@hackaugusto, please recheck above.

**Comment by hackaugusto** [comment]
Looks good, just two things:

- RaidenNode2 also needs to sign and handle the ContractReceiveChannelWithdraw

**Comment by hackaugusto** [comment]
Parent issue: #1383

**Comment by heikoheiko** [comment]
Why is this is a priority for Ithaka?

**Comment by rakanalh** [comment]
Related issue in Raiden contracts: https://github.com/raiden-network/raiden-contracts/issues/277
