### ISSUE TITLE
Implement cooperativeSettle

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1514]
`TokenNetwork` contract now has a `cooperativeSettle` method. It needs to be implemented in the Raiden client.

TODO:

- [ ] add a function that computes the final balances of the two channel participants, taking into consideration the `deposit`, `withdrawn`, `transferred`, `claimable_locked`, `unclaimable_locked` amounts for each participant. See https://github.com/raiden-network/spec/blob/4f68afad99275cf91e084e1af86da17414ab189b/smart_contracts.rst#settlement-algorithm
- [ ] add `cooperative_setttle` method to the `TokenNetwork` proxy.
- [ ] add 2 messages: `CooperativeSettleRequest` (for node requesting a cooperative settle signature from the partner node), `CooperativeSettle` (containing the cooperative settle signature from the partner node)
- [ ] add corresponding events: `SendCooperativeSettleRequest`, `SendCooperativeSettle`,  `ContractSendChannelCooperativeSettle`
- [ ] add event handlers for the above
- [ ] add corresponding state changes: `ActionCooperativeSettle`, `ReceiveCooperativeSettleRequest`,  `ReceiveCooperativeSettle`,  `ContractReceiveChannelCooperativeSettle`

Note - we have to make sure that `SendCooperativeSettleRequest` and `SendCooperativeSettle` are handled correctly and the final settlement balances are computed correctly for both participants.

**Comment by hackaugusto** [comment]
Parent issue: #1383

**Comment by hackaugusto** [comment]
> There MUST be only one cooperative settle signed message per channel, per participant.

I would say that different versions of the cooperative settle message can be signed, *as long as they represent the same balances*. This is required to fix race conditions where the channel participants try to coop-settle at the same time.

**Comment by hackaugusto** [comment]
Additionally, the node which starts the coop-settle must stop accepting new transfers, and the once the partner receives the request it too must stop accepting new transfers. Then both nodes must wait until both merkle trees are cleared, either the locks will be successfully unlocked or removed because they expired.

**Comment by heikoheiko** [comment]
Why is this is a priority for Ithaka?

**Comment by loredanacirstea** [comment]
Is this still `high priority`? I thought it was not -> to be included only if time permits.

**Comment by rakanalh** [comment]
Untagged... the feature is postponed until after Ithaca is released.

**Comment by hackaugusto** [comment]
related https://github.com/raiden-network/raiden-contracts/issues/1383
