### ISSUE TITLE
Reinstall filters at restart

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1561]
### Descritption

At restart we need to catch up with the logs that happened on the blockchain, that means on restart we need to reinstall the filters for all the known token network registries and token networks.

The current implementation relies on the utility methods from the smart contracts to list all the interesting smart contracts and reinstall the filters:

- [Registry.channelManagerAddresses](https://github.com/raiden-network/raiden/blob/a397d80fe3777f27e0a8d71b6e3548aa05f55701/raiden/smart_contracts/Registry.sol#L71-L88)
- [ChannelManagerContract.getChannelsParticipants](https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/ChannelManagerContract.sol#L83-L118)

The new version of the smart contracts don't have these utility methods, and must use the [available events](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contracts/TokenNetworkRegistry.sol#L24) to catch up with the smart contract state. For this to work properly, on restart, after the [state has been restored](https://github.com/raiden-network/raiden/blob/a397d80fe3777f27e0a8d71b6e3548aa05f55701/raiden/raiden_service.py#L240), the [filters must be installed](https://github.com/raiden-network/raiden/blob/a397d80fe3777f27e0a8d71b6e3548aa05f55701/raiden/raiden_service.py#L276-L279)

### Task list

- [ ] For the known token network registries:
  - [ ] Reinstall the filters using the last confirmed `from_block` from the previous run 
- [ ] For the known token networks:
  - [ ] Reinstall the filters using the last confirmed `from_block` from the previous run
- [ ] For the new token networks, created while the node was offline:
  - [ ] Install the filters either using the last confirmed `from_block` from the previous run, or the block number at which the new network was deployed
- [ ] Recreate the token network graph through the events instead of the current way that it's done through the getter
- [ ] Query all of the above filters and dispatch each event we get to the WAL. 
- [ ] Make sure that the [alarm task starts](https://github.com/raiden-network/raiden/blob/a397d80fe3777f27e0a8d71b6e3548aa05f55701/raiden/raiden_service.py#L273) after the filters have been reinstalled and processed (currently that is not the case)

**Comment by LefterisJP** [comment]
Working on this one

**Comment by LefterisJP** [comment]
Seems I need to do some small fixes for this issue still. Will take care of it since I am still assigned.
