### ISSUE TITLE
[META] Use more specific exceptions for the reasons a transactions may fail

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1966]
### Problem definition

To have better error handling and reporting Raiden should have specific exceptions for the different causes of transaction failures.

Example, currently [ChannelIncorrectStateError](https://github.com/raiden-network/raiden/blob/ea29dff47d84ceb80154694755dbe556b31eaba8/raiden/exceptions.py#L131) is used for [deposit](https://github.com/raiden-network/raiden/blob/ea29dff47d84ceb80154694755dbe556b31eaba8/raiden/network/proxies/token_network.py#L509-L512) and [close](https://github.com/raiden-network/raiden/blob/ea29dff47d84ceb80154694755dbe556b31eaba8/raiden/network/proxies/token_network.py#L563-L565) failures, on both cases there is no distinction if the channel never existed or if it was just closed. The first case is a bug because the identifier never existed, while the second may be a recoverable race condition among close and deposit.

### Transactions failures which are unrecoverable

General transactions failures which are bugs, and should not be handled:

- [ ] Transaction removed from the pool:
  - [ ] The nonce was invalid (too-low, too-high). Considered a bug when local signing is used.
  - [ ] The gas was invalid (lower than the minimum)
  - [ ] Another transaction overwrote it (same nonce, higher gas). Considered a bug if we are not trying to increase the probability of the transaction being mined (which is the case as of https://github.com/raiden-network/raiden/commit/d329583e492798e558f84ac1d839f345384d231d).
- [ ] The transaction had data and the `to` address never had bytecode
- [ ] The transaction failed because the `start_gas` was too low [OOG]
- [ ] A transaction which hit an assert

Smart contract transactions which are bugs and should not be handled (this assumes https://github.com/raiden-network/raiden/issues/1965):

- [x] Invalid operations on the token network:
   - [x] Open while a non-settled channel exists (as of https://github.com/raiden-network/raiden-contracts/commit/585f8a014a869eb3e5e0983c54fb1ccaa4cc6144 which disallows multiple channels for the same participants)
- [ ] Invalid operations on the netting channel:
   - [x] Deposit, Withdraw, or Close for a channel that was never opened
   - [x] Deposit, Withdraw, or Close for a channel that was settled
    - [x] Deposit or Withdraw which fails because the monotonic value decreased, because such operations are disallowed by the Raiden node.
   - [x] updateTransfer for a channel that was never closed
   - [ ] close with an invalid balance proof hash
   - [ ] updateTransfer with an invalid balance proof hash
   - [ ] settle with invalid balance proof data
   - [x] settle for a channel that was never closed (this assumes the settlement window is larger than the nº of confirmation blocks)
   - [x] settle for a channel that was closed but the settlement window is not over
   - [x] unlock while the channel was never settled (as of https://github.com/raiden-network/raiden-contracts/commit/585f8a014a869eb3e5e0983c54fb1ccaa4cc6144 which blinds the data from the monitoring services and required the settle to reveal the merkle tree root)

#### Transactions failures which are recoverable

General transactions failures which are races, and should be handled:

- [ ] The transaction start gas was higher than the block gas limit
- [ ] A transaction to a smart contract address which has selfdestructed
- [ ] A transaction which hit a revert

General smart contract transaction which are races, and should be handled:

- [x] Race operations on the secret registry:
  - [x] The secret is already registered
- [x] Race operations on the token registry:
  - [x] The token is already registered
- [x] Race operations on the token network:
  - [x] An open which fails because the channel is already open
- [x] Race operations on the netting channel:
  - [x] A deposit or withdraw which fails because the channel is closed
  - [x] A close fails because the channel is already closed
  - [x] A settle fails because the channel is already settled
  - [ ] An unlock fails because that participant channel state is already unlocked

### Tasks

- [x] Add two base exceptions `RaidenRecoverableError` and `RaidenUnrecoverableError`
- [ ] Individually implement the specific transactions, which should inherit from `RaidenRecoverableError` or `RaidenUnrecoverableError`, and raise from the smart contract proxies.
- [x] The Raiden event handler must handle `RaidenRecoverableError` by logging and dispatching a state change to clean up the transaction queue (#1950).

**Comment by LefterisJP** [comment]
So had a discussion with Augusto for how to handle this. We will tackle this together (and others can also help) and pick the cases of transaction failures one by one and create an issue for each one and solve it.

 Let us handle some of the first transaction errors to pave the way and then we can use them as a guide for everyone to pick the rest one by one and finish them fast.

**Comment by hackaugusto** [comment]
note: Initially we don't need to implement all these exceptions individually, we can start with two exceptions, one for unrecoverable cases and another for the recoverable cases, which allows the code to handle errors.

**Comment by hackaugusto** [comment]
Interesting, we have an bullet point for ` An unlock fails because that participant channel state is already unlocked` which was not implemented and resulted in the problem https://github.com/raiden-network/raiden/issues/3217 . @rakanalh I believe we discussed about this, but I do not recall why we didn't implement it, do you remember?
