### ISSUE TITLE
Simple lookahead strategy for gas and raiden transactions

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1998]
## Problem Definition

As discussed in the Raiden workshop we need a simple strategy to handle the user running out of gas while running raiden. For a more complete solution look at [this](https://github.com/raiden-network/raiden/issues/1861) issue.

## Task

- [x] Calculate/refer to the gas tables for the gas costs of all channel operations and add them to [constants.py](https://github.com/raiden-network/raiden/blob/4e0bfe55daea6f65ce439bc7a359b629dc0ae7cb/raiden/constants.py).
- [x] When user joins a token network calculate the gas required for the opening of all channels and the gas they would require for closing/setting them and if he does not have enough ETH to cover for it refuse to join the token network and provide a big warning message.
- [x] When the user opens a channel do the same as above but for only that one channel.
- [x] If the user opens Raiden and we don't have enough funds for an entire channel cycle warn the user though the CLI.

**Comment by palango** [comment]
Some questions/assumptions to clarify the logic:
- The minimal channel lifecycle we would define for this would be `ChannelOpen`, `ChannelClose` and `ChannelSettle`!?
- When doing the check for new channel opening we want to keep gas safed for each other open channel
- Raiden should only warn the user, but not exit or stop in any way.

**Comment by LefterisJP** [comment]
>The minimal channel lifecycle we would define for this would be ChannelOpen, ChannelClose and ChannelSettle!?

Better safe than sorry. Add an unlock in there too.

> Raiden should only warn the user, but not exit or stop in any way.

It should refuse to do the operation and print a big red fat warning. The UI should also consume that message and show it to the user.

> When doing the check for new channel opening we want to keep gas safed for each other open channel

I am not able to parse the above :). Can you elaborate a bit?

**Comment by palango** [comment]
> I am not able to parse the above :). Can you elaborate a bit?

Sorry. What I mean is the following scenario:
There are two open channels and we estimate that the channel lifecycle costs 100 wei. The balance is 250 wei. In that scenario we wouldn't allow opening another channel as we keep 200wei in escrow for the open channels.

**Comment by LefterisJP** [comment]
> Sorry. What I mean is the following scenario:

Ah yes indeed. I would say this is what we would need to do. Not really escrow, but just reserved for channel lifecycle of those channels.

The funny thing about this approach is that at the point of the query it may be enough but later if the gas price rises a lot the user may not have any funds. So the gas price that should be taken into account is tricky.

**Comment by palango** [comment]
> So the gas price that should be taken into account is tricky.

Yeah, for the start I will take the current gas price multiplied with a security factor. We can improve this later.
