### ISSUE TITLE
Adjust the codebase for the channel identifier change to uint256

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2000]
## Problem Definition

After all the changes proposed by https://github.com/raiden-network/raiden-contracts/issues/193
we will need to adjust the codebase to use the new `uint256` `channel_identifier`.

## Task

Adjust the codebase for the new `channel_identifier`.
This needs some thinking so the following list may be non-exchaustive:

1. [ ] Change the type of the channel_identifier in the [typing](https://github.com/raiden-network/raiden/blob/master/raiden/utils/typing.py#L26) module.
2. [ ] Grep for the above type and follow the codepaths to make sure the appropriate type is used
3. [ ] Adjust the channel_identifier in [messages.py.](https://github.com/raiden-network/raiden/blob/4e0bfe55daea6f65ce439bc7a359b629dc0ae7cb/raiden/messages.py#L76) and make sure that a uint256 is used for signing
4. [ ] Adjust the tests where needed
