### ISSUE TITLE
Improve the REST API pagination 

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2043]
## Problem Definition

Pagination is done either with filters for the block number or ids, neither of these filters allow the caller to control how many entries will be returned.

The API client cannot know how many events happen for a given block, so the number of entries is uncertain, and not all entries are returned, so pages filtered by ids may have holes in the response.

## Proposed solution

Change the rest API to include a `limit` and `offset` filters, with these filters the following semantics must hold:

- Elements must always have contiguous positions. This implies that a new request with offset starting at the previous offset + number of entries returned, will not return repeated elements.
- The API must return at most `limit` elements

## Task list

- [ ] Add to state changes and events sqlite tables a column to identify if the element should be expose through the APIs or not. 
- [ ] Update the raiden events API
- [ ] Update the channel events API

**Comment by hackaugusto** [comment]
@kelsos This is the issue I was talking about

**Comment by kelsos** [comment]
Nice, I had a look at the webui and it seems that the latest block is retrieved from the etheureum node using web3. The starting block when filtering the events is hardcoded in the webui.
