### ISSUE TITLE
Make Raiden recoverable

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#205]
## Problem Definition

For the Developer's preview we have made Raiden Restartable. Which means it can resume after a graceful shutdown. But it can't recover after a sudden shutdown such as a powercut.

## Dependencies

Depends on the following issues:

- ~Make the channel use a state machine~ ( https://github.com/raiden-network/raiden/issues/507)
- ~Write channel state changes in the WAL~ (https://github.com/raiden-network/raiden/issues/684)
- Take a snapshot of the entire state at specific intervals (https://github.com/raiden-network/raiden/issues/682)
- Recover from the WAL (https://github.com/raiden-network/raiden/issues/592)

## Description

Save raiden's state into disk so that the process can be safely restarted and continue from the last known valid state after a failure (eg. power failure).

## Solution

Goals:
- All the tasks must expose it's current state to allow serialization of the node state.
  - Current use of greenlet tasks can make important data "unreachable" because it's held in the stack.
- Save state of all the existing channels (latest balance proof and known secrets).
- Operations that change the node state need to be serialized on disk prior to being applied (related to: #69).
  - Employ a journaling strategy (write-ahead-log) for state trasitions.
  - Use snapshots for fast recovery

Subgoals:
- Improve testability

## Tasklist

- [x] Define a general architecture to define state transition that can be easily saved on disk #299 (Implemented by PR #266)
- [ ] Save the state in disk
  - [x] state transition into a WAL log #298
  - [ ] save snapshots in disk #682
- [x] Restartable Mediated Transfers  #301 (implemented by PR #413)
  - [x] send state transitions to the raiden architecture #302
- [x] Update the tasks route state
  - [x] Add new available routes #456
  - [x] Remove routes that may not be used anymore #468
- [x] Restartable Channel Graph
  - [x] Save the data about the nodes that cannot be recovered from the block chain in the disk
- [x] Restartable Channels
- [ ] Restartable Token Swaps #303

**Comment by LefterisJP** [comment]
After our latest call we re-define this issue as making Raiden recoverable.

The difference between recoverable and restartable lies in the fact that restartable assumes we can resume after a normal graceful shutdown, while recoverable means we can also recover from a sudden shutdown such as a power cut.

**Comment by LefterisJP** [comment]
Closing this issue in favour of its sub-issues. 

Also at least for the Red Eyes scope, snapshot and restartable token swaps are not included so judging by the bullet points this issue is done for red eyes.
