### ISSUE TITLE
Rename /transfers/* endpoint to /payments/*

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2084]
## Problem Definition

In Tenerife we decided that a payment is **The process of sending tokens from one account to another. May be composed of multiple transfers (Direct or HTL). A payment goes from Initiator to Target.**

In #1949 we add a view into the payment history. This issue is to rename the current `'/transfers/<hexaddress:token_address>/<hexaddress:target_address>'` entpoint.

### ToDo:
- [x] Rename `POST '/transfers/<hexaddress:token_address>/<hexaddress:target_address>'` to `POST '/payments/<hexaddress:token_address>/<hexaddress:target_address>'
- [x] Update the docs
- [ ] Update the WebUI

**Comment by LefterisJP** [comment]
> In Tenerife we decided that

Please do not mention that as a reason to do anything. I'd rather see links to documentation. I recall that conversation but it's not well documented so I at least added that definition to the glossary: https://github.com/raiden-network/raiden/pull/2095
Note: It's also in the raiden network [spec repo](https://raiden-network-specification.readthedocs.io/en/latest/terminology.html?highlight=payment#term-payment).
