### ISSUE TITLE
Correctly update network graph for non-participating channels

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2111]
## Problem Definition

Routing information is calculated from the internal network graph. External channels (that is channels that the node is not a participant of) are correctly added to the graph but currently not removed. This leads to problems like in issue #2101 

A problem when removing closed external channels is that the event doesn't include both participants. Therefore another mapping of `channel_identifier` ==> `participants` needs to be added.

### ToDo

- [ ] Add a `channel_identifier_to_participants` dictionary to the `TokenNetworkGraphState`
- [ ] Update all channel call to the `TokenNetworkGraphState` to update the above mapping as well
- [ ] Create a new `ContractReceiveRouteClosed` state change when external channels are closed
- [ ] Update the  `TokenNetworkGraphState` properly when a `ContractReceiveRouteClosed` is emitted.
