### ISSUE TITLE
Make sure the client crashes on every unhandled exception (new approach)

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#2201]
The raiden client is supposed to crash on every unhandled exception. However, unhandled exceptions that happen in spawned `gevent.Greenlet`s only crash their greenlet and do not bubble up on the greenlet tree by default. Therefore, every greenlet will be required to check for unhandled exceptions in its children and propagate them.

Our former approach to achieve this behavior was to patch gevent and mess with its exception handling. After several attempts and discussions involving @andrevmatos, @ulope, @hackaugusto and myself we came to the conclusion that there is no way to achieve the behavior we want by patching gevent without unmanageable side effects.

Replaces #1829 and #2123 

To do:

- [x] Revert gevent patching (#2171)
- [x] Enforce crashing on each unhandled exception within the rest API (#2179, fixed in #2196)
- [x] keep a list of long-running greenlets and watch for exceptions in them (#2208)
- [ ] avoid the spawn-and-forget pattern, parent should always keep track of children greenlets, rewrite functions where necessary

**Comment by andrevmatos** [comment]
@hackaugusto Yes, that's the plan

**Comment by jomuel** [comment]
@LefterisJP 
I guess 'avoid a pattern' was a confusing way to word it since we do not only need to avoid this pattern in the future, but also replace it where it occurs in the current code. Since so far there has only been a pr for raiden-libs, I suppose it is not done for the occurences in the main repo.

**Comment by LefterisJP** [comment]
Hmmm we need to discuss if this is changes we want at this moment in the client. I don't like issues with multiple bullet points as it does not make it easy to track. Can you please open another issue for this last bullet point?
