### ISSUE TITLE
Smoketest: Remove test dependencies

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2384]
## Problem Definition

The smoketest is intended to be a quick way of ascertaining basic functionality of a raiden node installation. 

Unfortunately it currently uses functionality from the `raiden.tests` package (and part of its code is even located inside that package).

This makes it impossible to run the smoketest from the distribution binaries or without installing the full development dependencies in source checkouts.

Refs: #1726, #771

## Tasks

- [ ] Move functionality used by the smoketest to `raiden.utils` or other appropriate places
- [ ] Move the smoketest implementation itself out of the `raiden.tests` pacakge
- [ ] Run the smoketest as part of the automatic packaging
- [ ] Add changelog entry

**Comment by konradkonrad** [comment]
With #5952 we are closer, but not there yet. The following comes from a locally built linux binary:
```
========================== SMOKETEST EXECUTION ERROR ===========================
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 835, in smoketest
    with stdout_manager, testchain_manager as testchain, matrix_manager as server_urls:
  File "contextlib.py", line 112, in __enter__
  File "raiden/utils/test_support/smoketest.py", line 289, in setup_matrix_for_smoketest
    from raiden.tests.utils.transport import matrix_server_starter
  File "/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "raiden/tests/utils/transport.py", line 19, in <module>
    from synapse.handlers.auth import AuthHandler
ModuleNotFoundError: No module named 'synapse'
```
So it seems, we'll need to ship `synapse` along with the main requirements.

**Comment by konradkonrad** [comment]
After adding the dependency, it turns out, that there are a couple more refactorings to do (read: move stuff out off `raiden/tests/....`). Still WIP.

**Comment by konradkonrad** [comment]
I closed https://github.com/raiden-network/raiden/pull/5952 -- in raiden pypi installations the `raiden.tests` package is available, therefore -- given test requirements+geth installed -- `smoketest` is available.
For binary distributions this issue still exists. If we face a situation with a large number of user support requests, we can re-evaluate if we want to fix this. If that is the case, there is also the quicker solution of ensuring distribution of `raiden.tests` in pyinstaller binaries.

**Comment by ulope** [comment]
That seems to be good enough. Closing this.
