### ISSUE TITLE
Recover old balance proof to settle with partner who uses it

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2414]
## Problem Definition

Part of #2214 .

During settle, our partner may try to cheat and use an old BalanceProof and not the latest one. We have to handle this case and recover the old balance proof from the WAL.

## Tasks

- [ ] Add balance hash to all state changes that have balance proofs. Perhaps only `SignedBalanceProofState` is enough.
- [ ] Query the WAL for the state change that has this balance proof hash
- [ ] Find the closest snapshot to that state, and replay the state, (just like we do when we restart -- just reapply state changes, and discard event. So no I/O) to recreate the state at the point of the balance proof.
- [ ] Use that state to obtain the balance proof and the recreated merkle tree to use in `settle()` and `unlock()`

**Comment by LefterisJP** [comment]
pushing to next milestone
