### ISSUE TITLE
Scenario player tasklist

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2554]
## Abstract

The current version of the scenario player is really good but there is always room for improvement.  So if you have ideas of features that could be added, and you consider that they will be a good addition to the scenario player, please write a comment describing your idea. 

Since I opened the issue I would like to add some of my ideas as well.
- [x] capability of opening channels with given ETH addresses. (#2680)
- [x] ability to join the token network ( especially useful with changing parameters such as ``joinable_funds``, ``channel_target`` and ``funds``).
- [x] possibility to assert for a specific response. #2579
- [x] leave token network. #2585 
- [x] Assert over channels opened via `join_network` where the exact peer nodes are not known (#2684)
- [x] spawning nodes on it's own (that would be a great thing to have, and useful when having to update the nodes to a certain version, if it's required) #2702

**Comment by palango** [comment]
Small bug:
```
Traceback (most recent call last):
  File "/Users/paul/Work/raiden/tools/scenario-player/scenario_player/main.py", line 124, in main
    assert_errors = runner.run_scenario()
  File "/Users/paul/Work/raiden/tools/scenario-player/scenario_player/runner.py", line 101, in run_scenaro
    wait_for_txs(self.client, mint_tx)
  File "/Users/paul/Work/raiden/tools/scenario-player/scenario_player/utils.py", line 81, in wait_for_txs
    raise ScenarioTxError(f"Timeout waiting for txhashes: {', '.join(txhashes)}")
TypeError: sequence item 0: expected str instance, HexBytes found
```

**Comment by LefterisJP** [comment]
Moved it to the next milestone but why is this in the milestone? A wishlist sounds like (1) a meta issue and (2) something that is not required.

**Comment by CosminNechifor** [comment]
@ulope would it make sens to add the ability to check the tokens a user has after the settlement took place?

**Comment by CosminNechifor** [comment]
Closing this. If we would need another feature I think is a good Idea to add a new issue describing the new feature.
