### ISSUE TITLE
Write scenarios for 'Join Network'

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2558]
# Write scenarios for "Join Network".

## Test cases:

Test | Description | Expected Behavior | Result
-- | -- | -- | --
J1 | Try to join a network with 100 tokens | 204 ACCEPTED - 3 open channels with 20 tokens capacity/each. 40 tokens will be kept for future transactions | Success
J2 | Try to join an already joined network | 204 ACCEPTED - since join_network is an idempotent function, it should return the same value but not open new channels | Success
J3 | Try to join a network after having left it and before settlement of all channels took place | 204 ACCEPTED - it will rejoin the network | Success
J4 | Try to join a network after having left it and after settlement of all channels took place | 204 ACCEPTED - should work as join a new token network | Success
J5 | Try to join non existing token network | 409 CONFLICT | CANNOT BE TESTED WITH SCENARIO PLAYER
J6 | Try to join network with 0 funds and default additional arguments | 409 CONFLICT | Success
J7 | Try to join a token network with the `joinable_funds_target` set to 0 | 204 NO CONTENT - `joinable_funds_target` is automatically set to 0.4 | **BUG It distributes 20 to each channel, see #2675**
J8 | Try to join a token network with the `initial_channel_target `set to 0 | 204 NO CONTENT - `initial_channel_target` is automatically set to default 3 | **BUG It distributes 20 to each channel, see #2675**
J9 | Try to join network with a prime number funds and default arguments | 204 NO CONTENT - there should be three channel open with [Prime * (1 - 0.4) / 3] rounded | Success
J10 | Try to join a network with 100 funds and `joinable_funds_target` set to 0.6 and `initial_channel_target` set to 6 | 204 NO CONTENT - works as described in #2678 | Success 
J11 | Try to join a network with 100 funds and `joinable_funds_target` set to 1 | 204 NO CONTENT - opens three channels with `deposit` and `balance` 0 | Sucess
J12 | Try to join a network with 100 funds and `initial_channel_target` set to 1 | 204 NO CONTENT - should just open one channel with 60 tokens | CANNOT BE TESTED WITH SCENARIO PLAYER - Manual test Success
J13 | Try to join a network with 100 funds and `initial_channel_target` set to 1 and `joinable_funds_target` set to 1 | 204 NO CONTENT - we expect 1 channel with deposit 0 and balance 0 | CANNOT BE TESTED WITH SCENARIO PLAYER - Manual test Success
J14 | Try to join a network with 100 funds and `initial_channel_target` set to 10 | 204 NO CONTENT - should open as many channels as possible in the respective network, rest of the tokens are reserved for opening channels with potential new-joiners | Success
J15 | Try to join network with 73 funds and `joinable_funds_target` set to 1 | 204 NO CONTENT - We expect 3 open channels with deposit 0 and balance 0 | Success
J16 | Try to join network with less than 5 tokens and default values | 204 NO CONTENT - We expect 3 open channels with deposit = 1 and balance = 1 token each | Success
J17 | Try to join network with `joinable_funds_target` set to >1 | 409 CONFLICT | **BUG Opens 3 channels with 0 balance and 0 deposit, see #2676**
J18 | Try to join network with `initial_channel_target` > participants in the network | 204 NO CONTENT - we expect as many channels open as possible whereas the rest of the funds are hold back to open a channel when new participants join, as described in #2678 | Success (write additional test for fifth node to join)
J19 | Try to join network and shut down node before all txs are mined,   then start the node again and check if the channels were created. | 204 NO CONTENT - should work like joining a network | Success

## Tasks
- [x] Give feedback on the written issue (edit it if needed)
- [x] Wait until "Join" and "Leave" tasks have been added to the SP (see #2554)
- [x] Write scenarios for the test cases
- [x] Execute scenarios for the test cases
- [x] Open issues for any bug which has been found
- [x] Upload scenario files to github

**Comment by CosminNechifor** [comment]
Removing ``Join a different network with same amount of tokens`` since it was already implemented [here](https://github.com/raiden-network/raiden/blob/9a0af181a384c75bf62c07e75592581c6dfbb1b6/raiden/tests/integration/long_running/test_token_networks.py#L91-L101) .

**Comment by Dominik1999** [comment]
Since I cannot edit the above entry anymore, here are the results 

| Test | Description | Expected Behavior | Result |
| --- | --- | --- | --- |
 J1 | Try to join a network with 100 tokens | 204 ACCEPTED - 3 open channels with 20 tokens capacity/each. 40 tokens will be kept for future transactions | Success |
J2 | Try to join an already joined network | 204 ACCEPTED - since join_network is an idempotent function, it should return the same value but not open new channels | Success |
J3 | Try to join a network after having left it and before settlement of all channels took place | 204 ACCEPTED - it will work as if we never joined the token network (basically it will go through the same process again) | ?
J4 | Try to join a network after having left it and after settlement of all channels took place | 204 ACCEPTED - should work as join a new token network | ?
J5 | Try to join non existing token network | 409 CONFLICT | CANNOT BE TESTED WITH SCENARIO PLAYER
J6 | Try to join network with 0 funds and default additional arguments | 204 NO CONTENT | ?
J7 | Try to join a token network with the joinable_funds_target set to 0 | 204 NO CONTENT - **Distribution unclear** | ?
J8 | Try to join a token network with the initial_channel_target set to 0 | 204 NO CONTENT - there should be no open channels but joining should be possible | ?
J9 | Try to join network with a prime number funds and default arguments | **?** | ?
J10 | Try to join a network with 100 funds and joinable_funds_target set to 0.6 and channel_target set to 6 | 204 NO CONTENT - **Distribution unclear** | CANNOT BE TESTED WITH SCENARIO PLAYER
J11 | Try to join a network with 100 funds and joinable_funds_target set to 1 | 204 NO CONTENT - **?** should open no channels, but reserve 100 tokens for another channel to be opened later | ?
J12 | Try to join a network with 100 funds and channel_target set to 1 | 204 NO CONTENT - should just open one channel with 100 tokens | CANNOT BE TESTED WITH SCENARIO PLAYER
J13 | Try to join a network with 100 funds and channel_target set to 1 and joinable_funds set to 1 | 204 NO CONTENT - but we cannot test this in general, since we don't know which channel will be open | CANNOT BE TESTED WITH SCENARIO PLAYER
J14 | Try to join a network with 100 funds and channel_target set to 10 | 204 NO CONTENT - should open no channels, but reserve 100 tokens for 10 channels with 10 tokens each | CANNOT BE TESTED WITH SCENARIO PLAYER
J15 | Try to join network with 73 funds and joinable_funds set to 1 | 204 NO CONTENT - **Distribution unclear** | ?
J16 | Try to join network with less than 5 tokens and default values | 204 NO CONTENT - **Distribution unclear** | ?
J17 | Try to join network and shut down node before all txs are mined,  then start the node again and check if the channels were created. | 204 NO CONTENT - should work like joining a network | ?
