### ISSUE TITLE
Write scenarios for Open Channel

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2559]
# Write scenarios for "Open Channel":

## Test cases that need to be implemented:

| Test | Expected behavior |
| --- | --- |
| Node opens 1 channel | 201 response code, and recive a NettingChannel object |
| Node tries opens a channel to a channel partner it already has a channel with | 409 status code meaning CONFLICT |
| Node opens 30 channels | Should work as described for one channel. |
| Node opens channel with non-existing channel partner and unregistred token address. | token is not registred and a CONFLICT(409) status code |
| Node tries to open a channel but it has not enough tokens for the initial deposit| The channel will be opened but the deposit will not be performed, also a 402 response will be given |
| Node tries to opens a channel and then restarts | After the  transaction was mined, and the node was restarted the the node should see the channel |
| Node was offline and the partner opened a channel | Channel should be visible once online |

## Tasks

- [ ] Add more cases (if possible)
- [ ] Write scenarios for the test cases
- [ ] Execute scenarios for the test cases
- [ ] Open issues for any bug which has been found
- [ ] Upload scenario files to github

**Comment by CosminNechifor** [comment]
In the current version of the scenario player, the following case can't be implemented: 
- ``Node tries opens a channel to a channel partner it already has a channel with`` (This can't be implemented yet because there is no way to check for the response)
- ``Node opens 30 channels`` (this can't be done yet, because in order to open a channel we would need a running node. A good solution would be for the scenario player to allow us to open channels with some eth addresses instead of nodes)
- ``Node opens channel with non-existing channel partner but valid address`` (same as above)
- ``Node tries to open a channel but it has not enough tokens for the initial deposit`` (there is no way  to check for a response)
