### ISSUE TITLE
Write scenarios for fund / top up channel

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2560]
# Write scenarios for fund / top up channel.

## Test cases that are implemented and tested by the scenario player:

| Test | Description | Expected behavior | Result |
| --- | --- | --- | --- |
| F1 | Try to open channel with no deposit and then try to top up 0 tokens | 200 SUCCESS and there should be a channel open with capacity 0 | Success |
| F2 | Try to deposit 1 time | 200 SUCCESS and channel capacity should be updated to the new value | Success |
| F3 | Try to deposit 10 times | 200 SUCCESS and channel capacity should be updated to the new value x 10 times |  Success |
| F4 | Try to deposit 100 times | 200 SUCCESS and channel capacity should be updated to the new value x 100 times | Success |
| F9 | Try to deposit 0 tokens | 200 SUCCESS and channel capacity should stay the same | Success |
| F10 | Try to deposit a negative amount - total_deposit = -1 | 409 CONFLICT and the error message "Amount to deposit must not be negative | Success |
| F11 | Try to withdraw ~ depositing a negative amount - set total_deposit = current number - 1 | 409 CONFLICT | FAILED - node responded with 200 -> [issue](https://github.com/raiden-network/raiden/issues/2630) |
| F12 | Try to deposit an incredibly huge number | 402 CONFLICT and the node should handle DepositOverLimit | Success |
| F13 | Try to deposit an incredibly small number 1 * 10^-18 | 200 SUCCESS and channel capacity increased by 1 * 10^-18 | Success |
| F16 |  Try to top up with more tokens than a user holds (Node tops up channels but has not sufficient funds) | 402 PAYMENT REQUIRED | Success |
| F19 |  Deposit to channel having enough eth to send a transaction | This is implicitly testes with all successful scenarios | Success |
| F20 |  Try to deposit and then kill node before the transaction was submitted to the blockchain | It should not see any deposit since the transaction was not sent | NOT TESTED |
| F21 |  Try to deposit and then kill the node, taking into account that the transaction was sent by the client on-chain | The channel balance should increase by the deposit | NOT TESTED |
| F24 | Try to top up one channel with all available on-chain balance | 200 SUCCESS and channel capacity should be updated to the new value | Success |
| F25 | Try to deposit to a channel that was closed | 409 CONFLICT | Success |

## Test cases that must be tested manually:

| Test | Description | Expected behavior | Result |
| --- | --- | --- | --- |
| F5 | Try to deposit to another node's channel | This should be possible | Not tested, since not possible to test with the client |
| F6 | Try to deposit to a channel that does not exist | 409 CONFLICT | Success |
| F7 | Try to deposit with an invalid token address (but valid token address) | 409 CONFLICT | Success |
| F8 | Try to deposit with an invalid partner address (but valid token address)| 409 CONFLICT | FAILED, node responded with 404 NOT FOUND | 
| F14 | Try to make a deposit bigger then Limit | 409 CONFLICT | FAILED - Node crashes all the time trying to deposit more than 100, see [here](https://gist.github.com/Dominik1999/a5950039e4d18d8eddcaa3d23013998c) |
| F17 | Try to join a network where 40% tokens weren't used yet, decrease the total_amount to the amount that's currently used | xxx |  NOT TESTED, moved to #2558  |
| F18 | Try to deposit to a channel without having eth to send a transaction | 402 PAYMENT REQUIRED | Success |
| F22 | Try to deposit, but shutdown node before tx is mined | The channel balance should increase by the deposit  | Success |
| F23 | Change IP after a deposit was done | The channel balance should increase by the deposit  | Success |

## Tasks

- [x] Give feedback on the written issue (edit it if needed)
- [x] Add more cases (if possible)
- [x] Write scenarios for the test cases
- [x] Execute scenarios for the test cases
- [x] Execute manual test cases
- [x] Open issues for any bug which has been found
- [x] Upload scenario files to github

**Comment by Dominik1999** [comment]
These are my scenarios for review. I executed them and put the results above. 
https://gist.github.com/Dominik1999/2ad7dc4d6c2fc9daad6364615650659f

**Comment by palango** [comment]
Closed by #2646
