### ISSUE TITLE
Write scenarios for one-hop mediated transfers

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2561]
# Write scenarios for one-hop mediated transfers:

## Test cases that need to be implemented:

| Test | Expected behavior |
| --- | --- |
| Node sends one transfer | 200 response code and the channel capacity should change |
| Node sends 10 transfers |  200 response code and the channel capacity should change |
| Node sends 1000 transfers |  200 response code and the channel capacity should change |
| Make transfer with a negative number | 409 CONFLICT |
| Make transfer with amount higher than current balance | 409 CONFLICT |
| Make a payment using an token address that is not EIP55 valid. | 409 CONFLICT |
| Make a payment using an invalid (not EIP55/ not binary/ unknown) partner address | 409 CONFLICT |
| Make a payment with a valid token address, that was not yet registered. | 409 CONFLICT |
| Send entire balance in one transfer | 200 response code and the channel capacity should change |
| Receive transfer of 1 token | capacity should change |
| Receive transfer of 100 token | capacity should change |
| Send two transfers with same amount and identifier | Performs as a normal payment https://gist.github.com/CosminNechifor/3b68f3008b61aa2af34181f60b48fd81 |
| Send transfer to node without a path | 409 CONFLICT |
| Send transfer after close has been called | 409 CONFLICT |
| Node sends one transfer with sufficient capacity and restarts | should work as normal payment |
| Node sends one transfer with sufficient capacity and shuts down | Should work as a normal transfer |
| Send transfer to offline node | 409 CONFLICT |

For each of the conflict status codes, check the channel state and ensure that it was not changed in anyway.

## Tasks

- [ ] Add more cases (if possible)
- [x] Write scenarios for the test cases
- [x] Execute scenarios for the test cases
- [ ] Open issues for any bug which has been found
- [ ] Upload scenario files to github

**Comment by andrevmatos** [comment]
I think direct transfers aren't currently exposed through the APIs (and we may not expose it soon, as we use mediated transfers even between neighbors because they're more reliable right now), so this one may not be feasible for now (as AFAICT, scenario players use the APIs)

**Comment by CosminNechifor** [comment]
@andrevmatos We were referring to cases strictly related to transfers between 2 Nodes N1 <-> N2  that's why we decided to separate them. Do you consider that this should be combined with mediated in only one issue?

**Comment by andrevmatos** [comment]
Ok, no, I think it'd be nice to have this as a separate test, in the sense that it's a particular case of mediated transfers, and could do some specific tests, but the underlying mechanism should be exactly the same as mediated transfers. We do have actual direct transfers in code, but as I said, it doesn't have some of the properties we'd like in practice as mediated transfers, so it's not used or exposed in the API.

**Comment by hackaugusto** [comment]
I edited the issue to remove the ambiguity

**Comment by czepluch** [comment]
Fixed by https://github.com/raiden-network/raiden/pull/2659
