### ISSUE TITLE
Write scenarios for Mediated Transfers (more than one-hop)

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2562]
# Write scenarios for mediated transfers (more then one-hop).

## Test cases that need to be implemented:

| Test | Expected behavior |
| --- | --- |
| Send one mediated transfer to a node that there is a path to and enough capacity | 200 response code and the channel capacity should change |
| Node sends 10 transfers |  200 response code and the channel capacity should change |
| Node sends 1000 transfers |  200 response code and the channel capacity should change |
| In A-B-C with 10 tokens in each channel, send payment from A to C of 2 tokens | 200 response code, C should receive 2 tokens. The channel capacity from A->B should be 8. The channel capacity from B->A should be 12. The channel capacity from B->C should be 8.  The channel capacity from C->B should be 12. |
| In A-B-C, send payment of 11 from A to C | Should not work as there is no path with enough capacity.   we should have a 409 Response code with the message "Payment couldn't be compleated (insufficient funds, no route to target or target offline)." |
| In A-D-C with 20 tokens in each channel, and A-B-C path also existing, try to send 5 tokens from A to C |  |
| In same scenario as above, try to send 11 tokens from A to C | Should work by being mediated through A-D-C, since there is no other path with enough capacity |
| Make payment with 2 mediators | 200 response code and the channel capacity should change |
| Make payment with n mediators | 200 response code and the channel capacity should change |
| In A-B-C, A makes payment to C and goes offline before C request secret reveal |  |
| In A-B-C, A makes payment to C and B goes offline after mediating the tx | Should work, but will use the secret registry |
| Should work, but will use the secret registry |  |
| Node sends mediated transfers and receiver shuts down | 409 CONFLICT |

## Tasks

- [ ] Ideally think about as many random cases
- [ ] Write scenarios for the test cases
- [ ] Execute scenarios for the test cases
- [ ] Open issues for any bug which has been found
- [ ] Upload scenario files to github
