### ISSUE TITLE
Write scenarios for Close channel

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2563]
# Write scenarios for Close channel

## Test cases that need to be implemented:

| Test | Expected behavior |
| --- | --- |
| Node closes one channel | The channel should not be visible anymore and we should have a 200 response code  |
| Node closes all its channels | Same as above, but for all the channels |
| Node closes channel and opens with exact same address a new channel, before the settlement takes place | 409 CONFLICT |
| Node closes channel and opens with exact same address a new channel, after the settlement takes place | Should receive 200 response code when it's closed, and 200 when it's open, plus the channel object  |
| Node tries to close a channel multiple times | 409 CONFLICT [here](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L1070-L1074) |
| Node closes the channel and restarts | The channel should be in closed state |
| Partner closes the channel | The channel should be in closed state |

## Tasks:

- [ ] Give feedback on the written issue (edit it if needed)
- [ ] Add more cases (if possible)
- [ ] Write scenarios for the test cases
- [ ] Execute scenarios for the test cases
- [ ] Open issues for any bug which has been found
- [ ] Upload scenario files to github
