### ISSUE TITLE
Write scenarios for Leave network

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2564]
# Write scenarios for Leave network

## Test cases that need to be implemented:

| Test | Expected behavior |
| --- | --- |
| Leave a token network | 200 Response code and all channels should be closed. Settlement period will start. |
| Leaving a payment network  where the all the channels are in the closed state  | Channels will remain the same since they were already closed. Settlement period will start. |
| Start leaving the token network then shut down the node in middle process |  |

## Tasks

- [ ] Give feedback on the written issue (edit it if needed)
- [ ] Add more cases (if possible)
- [ ] Write scenarios for the test cases
- [ ] Execute scenarios for the test cases
- [ ] Open issues for any bug which has been found
- [ ] Upload scenario files to github
