### ISSUE TITLE
Stress test for crashing nodes

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2570]
## Motivation

Test to test Raiden's restartability under different states of the protocol.

## ToDos

- [ ] In a integration test, with a few nodes:
  - [ ] Use a custom Raiden event handler class to randomly stop a node, and then restart it
  - [ ] Do multiple parallel transfers
  - [ ] Assert on the expected state of the nodes after the test is executed

**Comment by LefterisJP** [comment]
So far my only finding is that the test seems to hang due to perhaps the same stuck transfer issue that @ulope is working on. Will have to look deeper to make sure.

**Comment by LefterisJP** [comment]
Rebasing this one on latest master to see its current status. Lots of conflicts.

**Comment by LefterisJP** [comment]
rebased -- still fails
