### ISSUE TITLE
Include scenario player tests in a CI system

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2647]
## Problem description

For the moment the only CI system we have setup is Travis so we should include it there.
Such inclusion should be conditional. We should have a special commit tag `[ci scenario player]` to invoke the scenario player tests if we want them to be run on a commit. They should never be included by default (they take too long).

An additional idea is to make them run during the nightly run when there is not much stress on the Travis queue.

## Tasks for approach 1

- [ ] Create and maintain a specific testnet for these scenarios. Can't spam ropsten with them.
- [ ] Make them run in Travis at nightly runs
- [ ] Make them run conditionally if a commit has the `[ci scenario player]` commit tag.

In the future we should consider moving this to whichever other CI system we migrate to.

## Tasks for approach 2

- [ ] Run all scenarios in a remote server in a loop on a commit (latest master?) and send notifications by email if something breaks

Approach 2 can be improved with a UI and with requests to run also on a specific PR or a specific commit hash through the UI. But this is ideas for later.

---

I think I prefer approach 2

**Comment by nlsdfnbch** [comment]
continued in https://github.com/brainbot-com/devops/issues/28
