### ISSUE TITLE
Limit the log size

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2709]
## Problem Definition

Our logs can be rather verbose and grow in size very quickly. This can result in a lot of disk space being used by logging alone. In combination with the growing DB this can very quickly make raiden unusable in small environments like a raspberry pi or even a small VPS.

Related: [Raiden must quit when disk is full]](https://github.com/raiden-network/raiden/issues/675)

## Task

- [ ] Add a new argument `--max-log-size` which will determine the maxium acceptable log size. The value of 0 would disable log limiting and/or rotation.
- [ ] Figure out a sensible default for it. Perhaps 256 MB?
- [ ] Use python's [RotatingFileHandler](https://docs.python.org/3.6/library/logging.handlers.html#rotatingfilehandler) in order to set the logs to rotate when that size is reached. For now the rotation should probably just be to delete the old log.
- [ ] **Optional** - Perhaps in another issue: Implement a configurable rotation where the old log is uploaded somewhere (or emailed?) so that the system where raiden runs saves space and at the same time no logs are lost.

**Comment by ulope** [comment]
There are multiple tools specifically designed for this purpose (`logrotate` being the most well known). IMO it'd be a waste of our time to re-invent the wheel here. 

We only need to make sure that we're well behaved when the logfile is externally rotated, which we should already be since we're using a [`WatchedFileHandler`](https://docs.python.org/2/library/logging.handlers.html#watchedfilehandler).

**Comment by andrevmatos** [comment]
That's already done, at least for the `raiden-debug.log` files: it keeps at most the main/current file + 3 rotations, rotating at 5MB mark, meaning for the debug files it won't ever go over 20MB. At most we could enable the same rotation mechanics for the [optional] `--log-file` cli parameter

**Comment by LefterisJP** [comment]
This issue is no longer relevant. The log size is limited.
