### ISSUE TITLE
Client crashes if SendRefundTransfer was the last event in the DB when we settle

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3179]
## Problem Definition

When talking with @kelsos in Berlin about the scenario he has been testing he experienced the following stack trace:

```
2018-12-17 15:52:11.194950 [debug    ] Raiden event                   [raiden.raiden_service] greenlet_name=AlarmTask|Greenlet-2 node=504300c5 raiden_event={"channel_identifier": "3", "token_network_identifier": "0x15008736b8eDf6EaB458D18440876aBd65e57837", "_type": "raiden.transfer.events.ContractSendChannelSettle", "_version": 0}
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/tasks.py", line 102, in _run
  File "site-packages/raiden/tasks.py", line 138, in loop_until_stop
  File "site-packages/raiden/tasks.py", line 203, in _maybe_run_callbacks
  File "site-packages/raiden/raiden_service.py", line 568, in _callback_new_block
  File "site-packages/raiden/raiden_service.py", line 481, in handle_state_change
  File "site-packages/raiden/raiden_event_handler.py", line 94, in on_raiden_event
  File "site-packages/raiden/raiden_event_handler.py", line 474, in handle_contract_send_channelsettle
AttributeError: 'SendRefundTransfer' object has no attribute 'balance_proof'
2018-12-17T15:52:11Z <Greenlet "AlarmTask|Greenlet-2" at 0x7fafcfc7c248: <bound method AlarmTask._run of <raiden.tasks.AlarmTask object at 0x7fafcee0e400>>> failed with AttributeError

2018-12-17 15:52:11.217669 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=AttributeError("'SendRefundTransfer' object has no attribute 'balance_proof'",) running=True subtask=<Greenlet "AlarmTask|Greenlet-2" at 0x7fafcfc7c248: <bound method AlarmTask._run of <raiden.tasks.AlarmTask object at 0x7fafcee0e400>>> this=<RaidenService 504300c5>
2018-12-17 15:52:11.617865 [debug    ] Matrix stopped                 [raiden.network.transport.matrix] config={'available_servers': ['https://raidentransport.exchangeunion.com', 'https://persephone.raidentransport.digitalvirtues.com', 'https://raidentransport.ki-decentralized.com', 'https://raidentransport.mycryptoapi.com'], 'discovery_room': 'discovery', 'retries_before_backoff': 5, 'retry_interval': 5.0, 'server': 'auto', 'private_rooms': True} current_user=@0x504300c525cbe91adb3fe0944fe1f56f5162c75c:persephone.raidentransport.digitalvirtues.com greenlet_name=RaidenService|Greenlet-1 node=504300c5
2018-12-17 15:52:11.618949 [debug    ] Alarm task stopped             [raiden.tasks] greenlet_name=RaidenService|Greenlet-1 node=504300c5
2018-12-17 15:52:11.620349 [debug    ] Raiden Service stopped         [raiden.raiden_service] greenlet_name=RaidenService|Greenlet-1 node=504300c5
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/raiden_service.py", line 405, in _run
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AttributeError: 'SendRefundTransfer' object has no attribute 'balance_proof'
2018-12-17T15:52:11Z <Greenlet "RaidenService|Greenlet-1" at 0x7fafcfc7c148: <bound method RaidenService._run of <RaidenService 504300c5>>> failed with AttributeError

FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2018-12-17T15-521evoz0ml.txt
'SendRefundTransfer' object has no attribute 'balance_proof'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/ui/runners.py", line 209, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/raiden_service.py", line 405, in _run
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AttributeError: 'SendRefundTransfer' object has no attribute 'balance_proof'
2018-12-17T15:52:11Z <Greenlet "Greenlet-7" at 0x7fafcfc7cd48: stop_task(<RaidenService 504300c5>)> failed with AttributeError

2018-12-17 15:52:11.628521 [debug    ] REST API stopped               [raiden.api.rest] node=504300c5
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 425, in run
  File "site-packages/raiden/ui/runners.py", line 247, in run
  File "site-packages/raiden/ui/runners.py", line 214, in _start_services
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/ui/runners.py", line 209, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/raiden_service.py", line 405, in _run
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AttributeError: 'SendRefundTransfer' object has no attribute 'balance_proof'
[30377] Failed to execute script raiden-script
```

Looking at the code here:

https://github.com/raiden-network/raiden/blob/023554420534eb2ea8a1705bb7653e9f44d7d214/raiden/raiden_event_handler.py#L456-L477

It seems that if the last event for the balance proof we search for is a `SendRefundTransfer` we get an attribute error due to the balance proof being part of the transfer attribute and not of the parent object itself. 

This error could have been probably caught by mypy ... ?

## Task

- [x] Fix the attribute error by creating a property on `SendRefundTransfer`
- [x] Check for all state changes and events and see if they have a balance proof not accessible as a property. If they do perform the same fix.
- [x] Write some tests

**Comment by LefterisJP** [comment]
> Check for all state changes and events and see if they have a balance proof not accessible as a property. If they do perform the same fix.

Could not see any other occasion where a `state_change` or and `event` has a balance_proof and doing `x.balance_proof` would not work.
