### ISSUE TITLE
rc releases break automatic homebrew updating

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3407]
## Problem Definition

The automatic homebrew update functionality can't deal with prerelease `-rcX` suffixes and produces invalid formula updates.

## Tasks

- [ ] Fix formula updater
- [ ] Add automatic test to make sure formula is usable before pushing
- [ ] Mark -rc releases as pre-releases in homebrew

**Comment by LefterisJP** [comment]
@ulope Is this still needed? I think I saw homebrew being updated with latest rcs

**Comment by palango** [comment]
Closing for https://github.com/raiden-network/raiden/issues/6035
