### ISSUE TITLE
Implement a whitelist for smartcontract code

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#344]
### Goal

Validate the deployed smart contract's _byte code_.

- Detect if a buggy compiler version is being used and reject it.
- Detect if the smart contract is unknown, reject it because we cannot prove safety.

### Related

Add bad tokens to the tests #2725

### White list of curated code

The list is comprised of curated smart contract, each with the corresponding byte code hashes and metadata. The metadata must contain the compiler name/version with additional data to hash the smart contract code (details below).

### Hash

The intent is to white list the smart contract byte code, not a given instance of the smart contracts, for this reason the library addresses must be removed from the byte code. The hashing function must be applied over the *hexadecimal* (without prefixing "0x") representation of the byte code with the libraries addresses replace by zeros.

Steps to produce a white list entry:

- Compile the smart contract with the solc compiler _without_ informing the libraries addresses.
- Replace the addresses with zeros
- Ensure the byte code is hex encode without the leading "0x"
- Hash the result
- The entry must save:
  - The solc version
  - Each library address position
  - The solc flags that change the contract byte code (--optmize and --optmize-runs)
  - The smart contract name

Steps to verify the smart contract:

- On the proxy constructor retrieve the smart contract code through the `eth_getCode` JSON-RPC call.
- Ensure the result is hex encode without the leading "0x"
- For each white list entry of the corresponding contract:
  - Get the addresses positions and replace the content with zeros
  - Hash the result and compare, if equals success!
- If not match is found the supplied address has invalid code, then an exception must be raised.

### TODO

- [ ] Create an initial white list for each smart contract.
- [ ] For each `raiden.network.rpc.client` proxy add the required byte code check.
- [ ] Optionally add a command line flag to ignore the code hashes.

**Comment by LefterisJP** [comment]
Creating the metadata is not required at all since new solidity versions actually provide for it.

We should use the proposed methodology for contract metadata verification that solidity currently uses. There is no need to reinvent the wheel.

You can find all the details [here](https://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata).

All the requirements you are setting and even more are already contained in the metadata file, emitted by the solidity compiler. I say even more because even the number of optimizer runs can make a difference in the bytecode result.

Of course the actual usage of the deployed metadata is something we should do and write up in raiden, but in that case the issue is going to be much simpler. We would just need to read and evaluate the metadata to determine whether the contract is valid or not but no need to create these data ourselves.

**Comment by hackaugusto** [comment]
Can you provide the steps to validate a smart contract using the solc generated metadata?

**Comment by hackaugusto** [comment]
I'm closing. It had two objectives:

1. Detect if a buggy compiler version is being used and reject it.
2. Detect if the smart contract is unknown, reject it because we cannot prove safety.

For *1* we have implemented https://github.com/raiden-network/team/issues/31 , which should be sufficient.

For *2* is superseded by https://github.com/raiden-network/raiden/issues/3744 and https://github.com/raiden-network/raiden/issues/3746 , the first validates our smart contracts and the later external smart contracts.
