### ISSUE TITLE
User Policy - Raiden needs to choose a pathfinding service from ServiceRegistry

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3467]
## Introduction

Right now, Raiden will start using PFS once the `--path-finding-service` flag is provided. However, the PFS should be (for now) randomly selected from the user registry

## Tasks
- [ ] Remove the flag
- [ ] Query the service registry contract for the list PF service providers
- [ ] Randomly select a PF service provider and use it

Depends on #3581 

Expected: End of Feb, 2019.

**Comment by LefterisJP** [comment]
I don't remember where we last discussed this but I remember discussing that once we get the RSB list on-chain then this task should just be a random choice out of that list each time. User choice can be offered but makes no sense by default. The default should be a random selection out of the available pool of MSes.

**Comment by palango** [comment]
A preliminary API has been implemented (https://github.com/raiden-network/raiden-contracts/pull/541) and will be available after the next contracts release.
