### ISSUE TITLE
Dynamic fees

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3542]
Issue #33 added support for constant mediation fees charged by the mediators. The PFS changes fee handling in https://github.com/raiden-network/raiden-services/issues/368, using a separate fee message and allowing a wide range of fee calculation options.

- [x] Use new fee message as decided in https://github.com/raiden-network/raiden-services/blob/master/adr/003-mediation-fees.md
- [x] Prevent replay attacks by using signature and nonce
- [x] Remove `mediation_fee` from `NettingChannelState` (#4250)
- [x] Remove mediation fee from `UpdatePFS`
- [x] Respect privacy settings (see https://github.com/raiden-network/raiden/pull/4227)
- [x] Update newly set fees (from CLI) into the channels (#4250)
- [x] Allow setting both flat and proportional fees
- [x] Calculate mediation fees based on new settings when doing a mediation ( #4269)
- [x] ~~Decide whether we want to add support for setting imbalance fees right now or defer that to a later time.~~ We'll add the foundation now, and implement it asap.
- [x] increasing nonce to avoid replay attacks
- [x] Allow setting rebalancing fees (#4270 )
- [x] Update `FeeSchedule` on deposit and withdraw (#4285)
- [x] Make PFS mode default (#4305 )
- ~~Remove routing mode CLI option~~

**Comment by karlb** [comment]
> Remove routing mode CLI option

If we do that, we'll lose the `private` option. Do we want to introduce a `private-mode` flag instead?
