### ISSUE TITLE
[META] Make sure that docs.rainden.network is up to date with Alderaan

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#3775]
After we have made the Spec up to date with Alderaan, https://github.com/raiden-network/spec/issues/252

The docs - https://docs.raiden.network/ - must be checked to make sure that it reflects all software related to the Alderaan Release.

### List of changes
- [x] Explain people how to change the new docs
- [x] Add new API endpoint `/shutdown` 
- [x] Add mediation fee docs, https://github.com/raiden-network/raiden/issues/4696
- [x] Check arguments for each API endpoint, see https://github.com/raiden-network/raiden/issues/6180
- [x] Transfer Aldraan Mainnet Tutorial to docs.raiden.network, https://github.com/raiden-network/raiden/issues/6179
- [x] Update the "Quick Start" Section with the new Wizard, https://github.com/raiden-network/raiden-wizard/issues/101
- [x] Test Tutorials in docs with Alderaan, https://github.com/raiden-network/raiden/issues/6184
- [x] Remove links to old docs in Raiden README
- [x] Decide if we want/need to remove the old docs from the git repo @Dominik1999 
- [x] ...

### How to check the API
I think the best way to do it is to go through the docs and verify that the arguments given to a specific API call is the same as in the [rest.py](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py) file. Furthermore also checking that the returned json object has the fields specified in the api code.

**Comment by Dominik1999** [comment]
@czepluch can you manage that this issue get's closed soon? There will be no bigger changes in the Alderaan milestone anymore. Docs should be quite complete though

**Comment by czepluch** [comment]
I think the responsibility of this has been moved to Talel. But I will check up tomorrow.

**Comment by konradkonrad** [comment]
there is a new `/shutdown` api endpoint

**Comment by taleldayekh** [comment]
Changing the content of the new docs is pretty straight forward. Just log into https://www.gitbook.com/ and choose the `Raiden Network` space to start adding content. I'll need to grant initial access to whoever wants to add stuff so just ping me about it.

Pay attention to how the current content is structured and written and try to keep the same style when adding. Some general guidelines:
- Avoid walls of text, split the text into subsections that are easy overview (see current content)
- User bulleted lists with actionable steps written in an active voice whenever possible
- Make technical stuff easy to understand. Both non-technical and technical people will appreciate this (win-win)
- Graphics are nice when they make sense and they should follow the same principles as above
