### ISSUE TITLE
Autoformat Raiden's codebase with Black

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3839]
## Problem

The avoid future style discussions, the team has decided we should use [Black](https://github.com/ambv/black).

## TODO
- [ ] Add black to requirements
- [ ] Decide on what configs to customize and create a config file
- [ ] Run black on the whole codebase to change the code in-place.
- [ ] Integrate black into `make lint` to make sure the step fails in case a diff was found.

**Comment by rakanalh** [comment]
Duplicate of #3738
