### ISSUE TITLE
Drop UDP transport

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3894]
## Tasks list
- [ ] Remove the transport
- [ ] Cleanup messages & encoding modules from un-needed datastructures
- [ ] Remove UDP tests
- [ ] Cleanup CircleCI configs from UDP-related configs

**Comment by christianbrb** [comment]
Some left overs
- [ ] The documentation
- [ ] [Open Issues](https://github.com/raiden-network/raiden/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+udp) (maybe not all of them)
