### ISSUE TITLE
Increase test coverage on remaining raiden/transfer modules

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3993]
These modules are slightly below our coverage goal of 90%:

- [x] `raiden/transfer/node.py` (86%) #4005 
- [x] `raiden/transfer/views.py` (87%) #4009 
- [x] `raiden/transfer/channel.py` (88%) #4014 

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by konradkonrad** [comment]
The actual `unit` test coverage is unfortunately below what was written in the issue:
```
Name                                                     Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------------------------------
raiden/transfer/__init__.py                                  0      0      0      0   100%
raiden/transfer/architecture.py                            101     20     16      6    76%
raiden/transfer/balance_proof.py                            13      0      0      0   100%
raiden/transfer/channel.py                                 681     82    228     41    85%
raiden/transfer/events.py                                  277    102     12      4    62%
raiden/transfer/identifiers.py                              51     14     12      5    67%
raiden/transfer/merkle_tree.py                              58      2     30      2    95%
raiden/transfer/node.py                                    455    212    204     41    49%
raiden/transfer/secret_registry.py                          13      1      4      2    82%
raiden/transfer/state.py                                   671    195    154     55    66%
raiden/transfer/state_change.py                            473    144     32     13    68%
raiden/transfer/token_network.py                           103     11     34      8    86%
raiden/transfer/utils.py                                    35      4      4      1    87%
raiden/transfer/views.py                                   218    109    116     12    44%
```
this was run against current `master` (bca2235fd067b339838e0c271f3567491f8322bd).
