### ISSUE TITLE
Dataclasses - set all DCs as frozen

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#4018]
This is a follow up issue to #3869, #3253 and PR #3969.

## TODO
- [ ] Set `frozen` on all dataclasses
- [ ] Use `dataclasses.replace` to set create a new dataclasses with a mutated value.
- [ ] `__post_init__` will reject setting values, so find a way to overcome this.

**Comment by LefterisJP** [comment]
@rakanalh I think most dataclasses are frozen right now, no?

**Comment by rakanalh** [comment]
Not really, most of them are the non-frozen.

**Comment by LefterisJP** [comment]
Indeed, was looking at only a subset of files.

I started taking a look at this issue and doing some initial work.

 So one question here, do we really want to just blindly set all dataclasses to frozen even if the instances of the dataclasses are mutated often? Like with the pathfinding IOUs?

https://github.com/raiden-network/raiden/blob/8821730a2fc28642738dce08c9eac1351854dacb/raiden/network/pathfinding.py#L67

**Comment by rakanalh** [comment]
> I started taking a look at this issue and doing some initial work.

I also started working on this a while ago and stopped because `replace`ing the objects is going to be ALOT of work. Also in the example you've given, there are objects which mutate theirselves so that also somehow needs to change.

**Comment by LefterisJP** [comment]
> Also in the example you've given, there are objects which mutate theirselves so that also somehow needs to change.

It's not hard to change that. You just return a mutated object, for example at the IOU's `sign()` function.

The question I have is basically does it make sense? Why do this? If a particular dataclass is used as immutable then should we force the `frozen=true` and go through all these hoops? If yes why? What do we gain?

And if it makes no sense let's just modify the issue to be to set `frozen=True` to the actually immutable classes, and finish it within a day ;).

**Comment by rakanalh** [comment]
The general idea we want to achive here is have immutable objects especially in the state machine where any mutations would be performed on a copy of the object and this copy replaces the old value after the mutation happens. The gain would be:
1. We don't deepcopy chain state anymore.
2. This enables us to perform atomic changes where we can drop the state's copy after mutations if sanity checks fail. This in the existing implementation is error-prone.

**Comment by LefterisJP** [comment]
> We don't deepcopy chain state anymore.

So how will the new approach work though? At the moment we make a copy of the current state, name it next state and modify it during the state transition.

If we don't do that and all state classes end up being immutable we would need to be making multiple copies of each state object instance for each time any attribute is modified. So in a really deep state transition call from a state change that touches a lot of parts of the state we would make many many copies each time any state class attribute needs to be modified.

Is that a good idea? What is the benefit of that?

> This enables us to perform atomic changes where we can drop the state's copy after mutations if sanity checks fail. This in the existing implementation is error-prone.

I think that in this sentence you are actually answering my question from above but I can't understand it. Can you maybe explain the logic here a bit in more detail?
 

> especially in the state machine

So if it's not the state machine and the dataclass does not need to be immutable should we still enforce `frozen=True`? Why? Frozen data classes have a tiny performance penalty according to the [docs](https://docs.python.org/3/library/dataclasses.html#frozen-instances):

> There is a tiny performance penalty when using frozen=True: __init__() cannot use simple assignment to initialize fields, and must use object.__setattr__().

**Comment by karlb** [comment]
We use plenty of frozen dataclasses now:
```
$ ag '@dataclass' --nogroup | grep frozen | wc
    119     122    7192
```

There's certainly room for more optimization, but we should do that after spotting bottlenecks in a benchmark.
