### ISSUE TITLE
mypy: enable disallow_untyped_defs

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4033]
We should enable the mypy setting `disallow_untyped_defs` that requires us to type all function signatures.

### Modules
- [ ] `raiden.api`
  - [x] `raiden.api.objects`
  - [ ] `raiden.api.v1.encoding`
  - [x] `raiden.api.v1.resources` (#5432)
  - [x] `raiden.api.rest` (#5226)
- [x] `raiden.blockchain`
- [x] `raiden.messages`
- [x] `raiden.network`
  - [x] `raiden.network.transport.matrix.client` (#5359)
- [x] `raiden.storage`
- [x] `raiden.transfer`
- [x] `raiden.ui`
  - [x] `raiden.ui.runners`
- [ ] `raiden.utils`
  - [ ] `raiden.utils.profiling`
  - [ ] `raiden.utils.cli`
  - [ ] `raiden.utils.http`
- [x] `raiden.*.py`

**Comment by karlb** [comment]
We can live with it in the remaining modules for now. We fix the remaining cases when we touch the code for a different reason.
