### ISSUE TITLE
Consistent behavior for pruned blocks with parity and geth

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4204]
### Abstract

Currently it is known that when Raiden interacts with Parity using the web3 library an exception is raised when `call`ing at a pruned block. [ref](https://github.com/raiden-network/raiden/blob/997760ea55c602720f08bbf63495a2b13dc4c4f4/raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py#L20-L44).

However, this does not seem to be the behavior for Geth. The problem here is that our strategy for handling pruned state may not work.

### Task

- [ ] Write an assumption test for Geth that forces it to prune a block
- [ ] If necessary and possible, write a middleware for web3 to raise an exception on pruned blocks.
  - [ ] If not possible a new strategy for Geth has to be considered.
