### ISSUE TITLE
[tracking] Routing issues

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4236]
### PFS related
- [x] Send no IOU if not required (#4095)
- [x] Re-request PFS infos when necessary (#4100)

### Initiator
- [x] Don't request routes when direct channel with capacity is available
- [ ] Discard routes after some time (ref #4213)
- [x] Initiator should check the state of the partner nodes (#4036)

### Mediator
- [x] Use provided routes instead of requesting new ones (#3863)

**Comment by palango** [comment]
@konradkonrad @lullis Can you add any outstanding issues from working on source routing?

**Comment by palango** [comment]
Most of the stuff is done!
