### ISSUE TITLE
Introduce API endpoint to mint tokens

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#4277]
Related: https://github.com/raiden-network/webui/issues/11

In Raiden's WebUI, introducing a mint token button will require account unlocking and sending a transaction on-chain which is easier to be done via Raiden's API.

# TODO
- [x] Introduce API endpoint to mint a token if the token designated token supports it (Only on testnets for now, mainnet should not react upon calling this endpoint)
- [x] Write tests for the newly created endpoint.
- [ ] Update docs to explain usage of the endpoint

**Comment by kelsos** [comment]
@rakanalh does it make sense to have some kind of grouping for testing APIs? since this a mostly a testing API.

Also, it would be better if this endpoint is noop on mainnet. It could directly return some HTTP error if it is not on a testnet.

**Comment by rakanalh** [comment]
Seems like in the other issue there are 2 conflicting opinions about it. We can expose it to testnets only for now and see if we want to do that for mainnet as well.

**Comment by LefterisJP** [comment]
I talked about this with @kelsos over the weekend. 

>  Introduce API endpoint to mint a token if the token designated token supports it (Only on testnets for now, mainnet should not react upon calling this endpoint)

Sure only for testnets but where would the endpoint be? What is its spec? I propose we have a common url root path for all these testing endpoints.

**Comment by rakanalh** [comment]
IMO, we should expose the endpoint similar to https://raiden-network.readthedocs.io/en/latest/rest_api.html#get--api-(version)-tokens-(token_address)-partners

with a POST / PUT call instead of GET.

**Comment by LefterisJP** [comment]
> with a POST / PUT call instead of GET.

This would add additional logic. Essentially some conditionals on the endpoint which would determine if we are in production or not and then allow/block the new verb (POST/PUT).

If we have a root url for testing, we can just disable it completely for production, so no additional logic would be found in production for this minting thing.
