### ISSUE TITLE
Close open ends regarding routing / refunding - Meta-Issue

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4471]
There are some open ends regarding the routing / refunding behaviour of the Raiden Client. We should close those step by step. 

- [ ] Define / Specify default behaviour if the client doesn't use external pfs (internal routing vs. run local pfs)
- [ ] Code default behaviour for defined local routing incl. tests
- [ ] Define / Specify default behaviour with respect to refunding and mediation fees, according to https://github.com/raiden-network/team/issues/498
- [ ] Code default behaviour for defined refunding / mediation fees incl. tests
- [ ] ...

Do I miss anything?

**Comment by hackaugusto** [comment]
duplicate https://github.com/raiden-network/raiden/issues/4633
