### ISSUE TITLE
Rewrite existing scenarios acc. to principles and delete PFS6

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4590]
### Description
A detailed issue split from https://github.com/raiden-network/scenario-player/issues/216

Principles:
- always use `transfer` not `assert_pfs_routes`
- many small scenarios not big ones
- always with fees
- Instead of A -> B - > C write 0 -> 1 -> 2 within the comments

### Tasks

- [ ] Adjust ms1_simple_monitoring.yaml
- [ ] Adjust ms2_simple_monitoring.yaml
- [ ] Adjust ms3_simple_monitoring.yaml**
- [ ] Adjust pfs1_get_a_simple_path.yaml
- [ ] Adjust pfs2_simple_no_path.yaml
- [ ] Adjust pfs3_multiple_paths.yaml
- [ ] Adjust pfs4_use_best_path.yaml
- [ ] Adjust pfs5_too_low_capacity.yaml
- [ ] Delete pfs6_low_capacity.yaml
- [ ] Adjust pfs7_simple_path_rewards.yaml
