### ISSUE TITLE
Add mediation fee to spec and docs

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4696]
Currently we have to user docs explaining how mediation fees work and how to set them.
---

- [x] Update spec (tracked in the spec)
  - [x] Explain imbalance fees https://github.com/raiden-network/spec/issues/251
  - [x] Specify `PFSFeeUpdate` message (see https://github.com/raiden-network/spec/issues/287)
  - [x] Specify `PFSCapacityUpdate` message (see https://github.com/raiden-network/spec/issues/288)
  - [x] Proof read current spec to check if it is generally up to date.
- [x] Update docs.raiden.network and add info about mediation fees. Goal: user should know how to change those and how the fee mechanism work
   - [x] Check https://medium.com/raiden-network/dynamic-mediation-fees-in-raiden-explained-dbc29f032e4b for fee explanation and re-use whatever you can
   - [x] Explain imbalance fee with example - user must understand that the amount you send differed from the amount the receiver receives
   - [x] Explain to the user how to change fees
   - [x] Explain to the user how the pfs takes fees into account

**Comment by Dominik1999** [comment]
@karlb is this up to date now? Can we close?

**Comment by karlb** [comment]
The spec is up to date. I'm not sure what the expectations for the user docs are.

**Comment by Dominik1999** [comment]
for the docs, the goal is that the user knows how to set fees. Let's define together who could help us there. then we keep the issue open.

**Comment by Dominik1999** [comment]
@agatsoh and me we were both irritated in recent tests due to the fees. We tried to send very small amounts and we got `there is no route` because the value was too small for the default fees. This needs to be explained to the user. There must be a minimum amount a user can send (depending on the channel balance).

**Comment by palango** [comment]
> @agatsoh and me we were both irritated in recent tests due to the fees. We tried to send very small amounts and we got `there is no route` because the value was too small for the default fees. This needs to be explained to the user. There must be a minimum amount a user can send (depending on the channel balance).

I think explaining it only goes so far. If the UX of this is so bad, that even people who work with it don't get it then we should maybe set them to zero for now and enable them only in a subsequent release.

**Comment by Dominik1999** [comment]
can we somehow only have default flat and proportional fees or have at least a better error message?

**Comment by palango** [comment]
> can we somehow only have default flat and proportional fees

How would that solve the problem? The problem is, to my understanding, that the default fees are way higher then the amount and we forbid this in the client.

**Comment by Dominik1999** [comment]
yes, my idea is that with only flat and proportional fees we can give the user a good error message by calculating that before the transfer is executed. Like it is easy to calculate

- `x = amount to be sent`
- `ff = flat fee`
- `pf = proportional fee`

-> `if x * 1.2 < (x + ff) * (1 + pf) say No`

Just a thought

**Comment by karlb** [comment]
We definitively need a better error message. With that error message, no one is going look up the mediation fee chapter in the docs. At some point, we should also allow sending such payments if the user really wants.

I agree that we should do something about it, but adding explanations to the mediation fee chapter won't help. So I consider it out of scope of this ticket.

**Comment by karlb** [comment]
I created https://github.com/raiden-network/raiden/issues/6197, as this needs at least a code change for the error message.

**Comment by palango** [comment]
> yes, my idea is that with only flat and proportional fees we can give the user a good error message by calculating that before the transfer is executed.

That's nice, but it would also be ice to still allow small amounts in direct transfers.
