### ISSUE TITLE
Add scenarios to test mediation fees

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4748]
~~Blocked by https://github.com/raiden-network/raiden/issues/4844~~
~~Blocked by https://github.com/raiden-network/raiden/issues/4731~~
~~Blocked by https://github.com/raiden-network/scenario-player/issues/336~~
~~Blocked by https://github.com/raiden-network/raiden-services/issues/535~~

Follow up to https://github.com/raiden-network/raiden/issues/4710

Closes https://github.com/raiden-network/team/issues/567

- [x] Add flat fee scenario (#4920)
- [x] Add proportional fee scenario (https://github.com/raiden-network/raiden/pull/4950)
- [x] Add scenario that combines all three components (#4971)
- [x] Add imbalance fee scenario (https://github.com/raiden-network/raiden/issues/4969)

**Comment by palango** [comment]
Blocked by https://github.com/raiden-network/raiden-services/issues/535
