### ISSUE TITLE
Message upgradability

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#491]
## Problem Definition

Old and new releases of the software must be able to communicate, for this end the off-chain messages format must be forward and backward compatible. 

#### Approaches:

- Every message has a command identifier, when a message is modified a new identifier can be used to differentiate the data
- The serialization format used can support native forward/backward compatibility. By ignoring unknown fields and having default values when possible.
- The Raiden node must ignore messages with an unknown cmd id, and ignore unknown fields for known messages.

#### JSON

JSON can be used in a forward/backward manner if:
- No field without a default is ever renamed/removed. Allowing old versions to understand new messages
- The number of keys is not enforced, allowing new format versions to add fields
- If the above cannot be done, by using a type of message

#### Version handshake

A Raiden node must not assume the node which it's communicating to is running the same version, therefor it must be able to gather information about the capabilities of the partner node. The handshake will be implemented by a new message, which is not known by the first release of the software, to handshake the node's capabilities.

### Task list

- [ ] Add a handshake message
- [ ] Add a state change to change the protocol version of a partner node
- [ ] Add into a state object a way to represent the current version of the node
- [ ] Periodically check the node's capabilities (maybe this should be done in the healtcheck)

**Comment by hackaugusto** [comment]
duplicate: #2161
