### ISSUE TITLE
Long Running Scenario which is more aligned with UAT and distributed environment

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5177]
## Abstract
A long running scenario needs to be created which tests complete raiden stack along with contracts, transport, Raiden client, blockchain, eth-client, monitoring service, pathfinding service and service contracts

## Motivation
1. https://github.com/raiden-network/team/issues/643
2. https://github.com/raiden-network/raiden/pull/2763

As mentioned in the issue [643](https://github.com/raiden-network/team/issues/643) of the raiden team repo we need a scenario which is focussed on
1. Complete user acceptance 
2. Testing in a distributed environment.

## Tasks
- [ ] Get it running (disable fees)
- [ ] Create an issue in Raiden and implement
- [ ] Make a specification how to extend it with Alderaan functionalities (fees, etc.)

## Specification
Create a scenario which is:
- [ ] long running
And tests the complete raiden stack like 
- [ ] Raiden Client 
- [ ] Raiden Contracts
- [ ] Matrix Transport
- [ ] Ethereum Client
- [ ] Monitoring Service 
- [ ] Pathfinding Service
- [ ] Service Contracts 
- [ ] Mediation fees (different configurations)

**Comment by christianbrb** [comment]
The long-running scenario is working
