### ISSUE TITLE
[META] - Payment couldn't be completed because: there is no route available  [DO NOT PICK UP]

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5433]
# Meta Issue for the Symptom "No route found"
Recently we have seen some scenarios failing with the message `Payment couldn't be completed because: there is no route available`. This is a Meta Issue to track the Symptom and to be able to close all related issues to that. 

- Possible root cause: https://github.com/raiden-network/raiden-services/issues/673
- Issue with logs: #5357 
- Issue with logs: #5337 
- Issue with logs: #5375 
- Issue with logs: #5400 

It does not make sense to keep those issues open, since we try to reproduce the issues to get fresh logs together with the pfs logs. Without the corresponding pfs logs, we cannot analyze further. 

## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [x] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [x] The Raiden node was never restarted. If yes please provide more info.
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

**Comment by Dominik1999** [comment]
Have seen it again: 
MFEE3 failed last night with `Payment couldn't be completed because: there is no route available`
- [Node1](http://68.183.70.168:8000/scenario-player/scenarios/mfee3_only_imbalance_fees/node_9_000/)
- [Node2](http://68.183.70.168:8000/scenario-player/scenarios/mfee3_only_imbalance_fees/node_9_001/)
- [Node3](http://68.183.70.168:8000/scenario-player/scenarios/mfee3_only_imbalance_fees/node_9_002/)
- Scenario Logs: http://68.183.70.168:8000/scenario-player/scenarios/mfee3_only_imbalance_fees/scenario-player-run_mfee3_only_imbalance_fees_2019-12-05T00%3A32%3A21.log

@karlb @palango

**Comment by karlb** [comment]
The error is `NoRouteFound('Source not online')"`, so it looks like we're having problems with the presence handling.

**Comment by palango** [comment]
> The error is `NoRouteFound('Source not online')"`, so it looks like we're having problems with the presence handling.

Damn, and I just removed the presence logging yesterday: https://github.com/raiden-network/raiden-services/pull/679

**Comment by Dominik1999** [comment]
@karlb can you add to the error message `Source not online but payment received - stupid source!`

**Comment by karlb** [comment]
The PFS has not received a ChannelOpened event for the potential initiator, so it does not track its presence and assumes that it's offline when it requests a route.

**Comment by Dominik1999** [comment]
so that does not sound matrix related, right?

**Comment by karlb** [comment]
Yes, that's not matrix related. It looks like we're skipping a block whenever a new channel is created. Should be reproducible in a unit test.

**Comment by Dominik1999** [comment]
@Dominik1999 to add logs from friday afternoon

**Comment by Dominik1999** [comment]
Logs from Fri 6th of December 15:00h CET

- SP logs http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-06T14%3A00%3A21.log
- Node 0: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_2_000/
- Node 1: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_2_001/- - Node 2: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_2_002/- - Node 3: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_2_003/- - Node 4: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_2_000/

**Comment by agatsoh** [comment]
On 7th December 2019 The BF4 scenario fails has a `No route available` failure

```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'lock_timeout': 30}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-12-07 02:01:41.228116",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:55899/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x0B336fB2F7E68A316dDE5E08a00a7c3Fb4C426b3. Expected 2..: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

what exception say:

1. `Payment couldn't be completed because: there is no route available`

2. while fetching request

`http://127.0.0.1:55899/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x0B336fB2F7E68A316dDE5E08a00a7c3Fb4C426b3`

3. Failure occurs at line 81

`- transfer: {from: 0, to: 3, amount: 1_000_000_000_000_000, lock_timeout: 30}`


https://drive.google.com/drive/folders/13DV21NX3X_vKUOpRIobhQUA0w8sx1vs6?usp=sharing

**Comment by karlb** [comment]
Both of the two cases directly above are caused by `NoRouteFound('Source does not have a channel with sufficient capacity')`. This message is surprising, considering that the previously processed CapacityUpdates look good (output from the PFS log for @agatsoh's BF4 error):

```json
{
  "message": {
    "signature": "0x022c0503436d6d9a636c1272421bef60ed092abba32699c70cb021b5e1af848f758b1cef7751e2b8be3d18dae14c943da962df27993e837f8161f785155276711b",                                                                                                     
    "canonical_identifier": {
      "chain_identifier": 5,
      "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6",
      "channel_identifier": 5090
    },
    "updating_participant": "0x512776974e648921Fa2Ccd829E1f29389560fd28",
    "other_participant": "0xD2298fd940C67Ae209cA504825f0D5C6e8261ADf",
    "updating_nonce": 0,
    "other_nonce": 0,
    "updating_capacity": 1e+18,
    "other_capacity": 1e+18,
    "reveal_timeout": 20,
    "type_name": "PFSCapacityUpdate"
  },
  "event": "Received Capacity Update",
  "level": "debug",
  "logger": "pathfinding_service.service",
  "timestamp": "2019-12-07 01:59:57.076776"
}
{
  "message": {
    "signature": "0x8596a8fa3ee973e298d2e6e9bdeebaa5e179658322bd7a747133363501a41bfa1594f1025a26d6c650e7abe45afcc9e435385554934d54208660c1e9333c60731c",                                                                                                     
    "canonical_identifier": {
      "chain_identifier": 5,
      "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6",
      "channel_identifier": 5090
    },
    "updating_participant": "0xD2298fd940C67Ae209cA504825f0D5C6e8261ADf",
    "other_participant": "0x512776974e648921Fa2Ccd829E1f29389560fd28",
    "updating_nonce": 0,
    "other_nonce": 0,
    "updating_capacity": 1e+18,
    "other_capacity": 1e+18,
    "reveal_timeout": 20,
    "type_name": "PFSCapacityUpdate"
  },
  "event": "Received Capacity Update",
  "level": "debug",
  "logger": "pathfinding_service.service",
  "timestamp": "2019-12-07 01:59:57.846347"
}
```

**Comment by Dominik1999** [comment]
We have seen that tonight three times:
- BF1: 
- - [SP Logs](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-10T22%3A01%3A44.log) 
- - [Node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_9_000/)
- -  [Node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_9_001/)
- -  [Node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_9_002/)
- -  [Node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_9_003/)
- -  [Node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_9_004/)
- BF2:
- - [SP Logs](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/scenario-player-run_bf2_long_running_2019-12-10T23%3A39%3A52.log) 
- - [Node0](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_000/)
- -  [Node1](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_001/)
- -  [Node2](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_002/)
- -  [Node3](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_003/)
- -  [Node4](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_004/)
- PFS8:
- - [SP Logs](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/scenario-player-run_pfs8_mediator_goes_offline_2019-12-11T04%3A16%3A22.log)
- - [Node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_000/)
- - [Node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_001/)
- - [Node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_002/)
- - [Node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_003/)
- - [Node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_004/)

**Comment by palango** [comment]
For BF1 I see:
```json
{
  "event": "Pathfinding Service can not find a route: Target not online (2201).",
  "logger": "raiden.network.pathfinding",
  "level": "info",
  "timestamp": "2019-12-10 23:39:45.594536"
}

```

**Comment by palango** [comment]
For BF2:
```json
{
  "event": "Pathfinding Service can not find a route: No route between nodes found. (2201).",
  "logger": "raiden.network.pathfinding",
  "level": "info",
  "timestamp": "2019-12-11 00:25:23.166211"
}
```

**Comment by palango** [comment]
For BF6:
```json
{"error": "ServiceRequestIOURejected('The provided payment is lower than service fee. (2104)')", "event": "Pathfinding Service rejected IOU", "logger": "raiden.network.pathfinding", "level": "debug", "timestamp": "2019-12-11 00:34:11.054577"}
{"log_message": "The provided payment is lower than service fee. (2104)", "event": "An error with the path request occured", "logger": "raiden.routing", "level": "warning", "timestamp": "2019-12-11 00:34:11.055220"}

```

**Comment by ulope** [comment]
The server-side presence monitoring shows this:

`@0xd2de5af1c5bc99837a70f09b31bd339de24b739d:transport04.raiden.network`

- `transport01`:
  - `2019-12-10 22:54:21.766880`: `<UserPresence.ONLINE: 'online'>`
  - `2019-12-10 23:38:24.389990`: `<UserPresence.OFFLINE: 'offline'>`

- `transport03`:
  - `2019-12-10 22:03:11.255074`: `<UserPresence.OFFLINE: 'offline'>`
  - `2019-12-10 22:03:28.593282`: `<UserPresence.ONLINE: 'online'>`
  - `2019-12-10 23:38:24.034341`: `<UserPresence.OFFLINE: 'offline'>`


(Unfortunately there are no records from transport02 and 04, I assume that's because we had the disk full issue during that time)

**Comment by palango** [comment]
> So this does not look like a return of the presence issue since all servers agree about the online state and see the correct state update within ~2s of each other.

With presence issue I meant more that we're seeing online nodes (hopefully) as offline.

**Comment by palango** [comment]
What's interesting about BF2:

The last `sync` call, was at **00:25:14**, which is 9secs before the PFS request.

```
{
  "node": "0x0Ed0a3F4a3B95b3f1118eCca2E856BcD8cb632c8",
  "first_sync": false,
  "sync_token": "s1370554_915524_0_35_973_5_1_32899_1",
  "current_user": "@0x0ed0a3f4a3b95b3f1118ecca2e856bcd8cb632c8:transport04.raiden.network",
  "presence_events_qty": 14,
  "to_device_events_qty": 0,
  "rooms_invites_qty": 0,
  "rooms_leaves_qty": 0,
  "rooms_joined_member_count": 0,
  "rooms_invited_member_count": 0,
  "rooms_join_state_qty": 0,
  "rooms_join_state_events_qty": 0,
  "rooms_join_ephemeral_events_qty": 0,
  "rooms_join_account_data_events_qty": 0,
  "event": "Starting _handle_response",
  "logger": "raiden.network.transport.matrix.client",
  "level": "debug",
  "greenlet_name": "GMatrixClient.listen_forever user_id:@0x0ed0a3f4a3b95b3f1118ecca2e856bcd8cb632c8:transport04.raiden.network",
  "timestamp": "2019-12-11 00:25:14.524498"
}
{
  "node": "0x0Ed0a3F4a3B95b3f1118eCca2E856BcD8cb632c8",
  "current_user": "@0x0ed0a3f4a3b95b3f1118ecca2e856bcd8cb632c8:transport04.raiden.network",
  "event": "Sync called",
  "logger": "raiden.network.transport.matrix.client",
  "level": "debug",
  "greenlet_name": "GMatrixClient.listen_forever user_id:@0x0ed0a3f4a3b95b3f1118ecca2e856bcd8cb632c8:transport04.raiden.network",
  "timestamp": "2019-12-11 00:25:14.525826"
}

```

**Comment by Dominik2002** [comment]
This issue cannot be worked on atm. We first fix #5498 and see if it happens again
