### ISSUE TITLE
Update to web3 5.x

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5467]
This brings us some goodies:
- Istanbul enabled test for the contracts: https://github.com/raiden-network/raiden-contracts/issues/868
- Stricter typing of the web3 API: https://github.com/raiden-network/raiden/issues/4900
- Fix some deprecation warnings: https://github.com/raiden-network/raiden/issues/3727

### Docs
- Migrations docs: https://web3py.readthedocs.io/en/stable/v5_migration.html
- Release notes: https://web3py.readthedocs.io/en/stable/releases.html

### Tasks
- [x] Merge https://github.com/raiden-network/raiden-contracts/pull/1339
- [x] Create contracts release
- [x] Update requirements
- [x] Run stress test as metric before and after the change -  there is timing info and plot histogram before and after

**Comment by palango** [comment]
The PR for the contracts is here and brings roughly 20% reduction in test runtime: https://github.com/raiden-network/raiden-contracts/pull/1339
