### ISSUE TITLE
[Meta] - Analyzing and pot. replacing deepcopy for matrix performance  

### ISSUE THREAD

**Issue by Dominik2002** [raiden-network/raiden#5565]
## Goal
We want to work on #5498 and sync with Matrix in less than 20s. Our flamegraph analysis showed that we spend a lot of time deepcopying messages, see https://github.com/raiden-network/raiden/issues/5498#issuecomment-566951011. So here, we might improve performance a lot.

## Approach (as discussed in Planning Session 06.01.)
- [x] Simplest thing: Log how long a deepcopy in the state machine takes when we do it
- [x] Profile how long one deepcopy takes and then create a budget ... create profile with node that has full state 
- [x] Implement benchmark for time to deepcopy
- [x] Try treecopy and compare against benchmark, see #5543

**Comment by karlb** [comment]
Closed by https://github.com/raiden-network/raiden/pull/5574.
