### ISSUE TITLE
Create TestMatrixTransport instead of monkey patching

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5652]
Currently monkey patching is used in many integration tests to see if matrix sends the correct messages (e.g. `test_pfs_send_capacity_updates_on_deposit_and_withdraw`)

Instead we should create a testing subclass of `MatrixTransport` that stores the messages for later access.

### Tasks
- [x] Subclass `MatrixTransport` and store sent (direct/broadcasted) messages (#5644)
- [x] Inject class into the integration tests (#5644)
- [x] Update tests and remove monkeypatching

**Comment by palango** [comment]
Fixed in cc8fdb34e60fb140e5ff0aec03a4e61b86187697
