### ISSUE TITLE
Implement informed connection strategies for ConnectionManager

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#576]
## Problem Definition
Follow up for #83 
The current connection manager implementation (see #400) doesn't do any informed ordering of potential channel partners.

## Solution

After simulations of different connection strategies we should replace the stub `raiden/connection_manager.py::ConnectionManager._select_best_partners` with a method that optimizes connectivity goals.

## Todos (some from previous issue)
- [ ] create a modeling for channel selection
- [ ] replace `raiden/connection_manager.py::ConnectionManager._select_best_partners` with a better strategy
- [ ] use a balancing channel partner selection strategy (select channel partners with a higher probability of funded back channels) 
- [ ] develop performance monitoring for channels (flag underperforming channels for eventual replacement)
- [ ] implement balancing (i.e. open new channels on bad performance)
- [ ] allow for user preferences for the above behavior

**Comment by karlb** [comment]
Closed in favor of https://github.com/raiden-network/raiden/issues/4730#issuecomment-704084005
