### ISSUE TITLE
Improve Matrix Server Performance - Back to Split Mode

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5884]
We cannot run all 24 scenarios in parallel. So we want to increase the performance of our test Matrix Servers (transport01 - transport04) in several steps. After every step we can test again how many parallel runs would break the setup. 

- [x] Step 1: Put Matrix server on better CPUs (non-split mode)
- [x] Step 1: Check if parallel execution (PE) works
- [x] Step 2: Put new Matrix servers up (with CPUs of Step 1) with split mode
- [x] Step 2: Test if presence issue is being introduced (#5943)
- [ ] Step 3: Put our Test Matrix Server (transport01 - transport04) into split mode (#5944)
- [ ] Step 3: Test PE with some scenarios and increase number (#5945)

**Comment by Dominik1999** [comment]
@hackaugusto helps with the script to check presence

**Comment by Dominik1999** [comment]
closing this due to the splitting of the issue
