### ISSUE TITLE
Raiden 0.200.0-rc3 encounters MatrixSyncMaxTimeoutReached exception

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#6037]
## Problem Definition
The raiden node while running encounters a `MatrixSyncMaxTimeoutReached` and closes off.
```
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
    run_services(kwargs)
  File "raiden/ui/runners.py", line 69, in run_services
    signal_received = stop_event.get()
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 307, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 297, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 277, in gevent._event.AsyncResult._raise_exception
  File "gevent/_compat.py", line 62, in reraise
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/raiden_service.py", line 394, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  75.37834636901971s > 75s. The thread had 97 context_switches, and idled 0.7093641214980189% of the time.
```

The node log
https://drive.google.com/open?id=1vyG3G6ROGraFZwJR47nbuuU0bD90fT2p

DB
[node_aa1ab1fd_MatrixSyncMaxTimeoutReached_error.tar.gz](https://github.com/raiden-network/raiden/files/4415437/node_aa1ab1fd_MatrixSyncMaxTimeoutReached_error.tar.gz)

# Todos

- [x] check if Environment==Production
- [x] What were the test parameters -> Test setup in production mode? 
- [x] Check if error message is in sync with code
- [ ] Possibly slow internet connection?

**Comment by agatsoh** [comment]
I used `development` environment
The way in which I started the node
`./raiden-v0.200.0-rc3-linux-x86_64 --pathfinding-service-address=https://pfs.t01.testtransport.raiden.network --matrix-server=https://t01.testtransport.raiden.network --eth-rpc-endpoint https://rpc.slock.it/goerli --api-address "http://localhost:5010" --keystore-path /home/devaki/snap/geth/477/.ethereum/keystore/ --address 0xAa1Ab1fDA93e14c2d564B25Ba08c9d374F5F9541 --network-id goerli --environment-type development --log-file node-Aa1Ab1-goerli.1stApril2020.log --log-config "raiden:debug" --password-file password_file.txt --accept-disclaimer --enable-monitoring`

**Comment by ulope** [comment]
## Result of ToDos

1. Node was run in development mode (as confirmed by @agatsoh above)
1. The exception is correctly only raised in development mode
1. The message does *NOT* accurately reflect the code. What's measured is `start_of_previous_sync` - `start_of_current_sync` 
1. The log does not contain in which mode the node is started. (We already have an issue for that: #4618)

That means this is not a critical issue but still needs some follow up on at least 3. (and 4.)

**Comment by Dominik1999** [comment]
Follow up issues for 
3. https://github.com/raiden-network/raiden/issues/6064
4. https://github.com/raiden-network/raiden/issues/4618
