### ISSUE TITLE
[META] Execute Alederaan Testplan with on Mainnet

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6050]
Since https://github.com/raiden-network/raiden/issues/5990 was successful, we move on to mainnet testing. 

## Executing the testplan on mainnet

- [x] Verify test plan is executable on Mainnet, open issues 
- - [x] Adapt Scenario Player to be executable on Mainnet @ulope and #6061 
- - [x] Get necessary tokens for SP to execute
- [x] Execute test plan on Mainnet, see [here](https://docs.google.com/spreadsheets/d/1An2fZ1qZH9Cgq1bsFuLhpzl_y2OFpBAvuZZgYcJalxY/edit#gid=0)
- - [x] @karlb and @czepluch test smart contract parts (SC steps)
- - [x] @fredo and @czepluch  test RSB parts (RSB steps)
- - [x] @Dominik1999 organizes scenario testing, see https://github.com/raiden-network/raiden/issues/6140 (Client steps)
- - [x] Whole Raiden team does manual testing (Client-3 step)
- - [x] results need to be logged
- [x] @czepluch and @GataKamsky give the approval to proceed to Alderaan Mainnet Release 

Critical issues found:
None so far
