### ISSUE TITLE
Scenario Testing on Mainnet

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6140]
## All scenarios must be green on mainnet as a last step before the release 
To ensure Raiden works also on the Ethereum Mainnet as expected, we need to see all scenarios being successfully executed on mainnet at least once. 

## The first test runs on mainnet was not successful, we need to work on

- [x] Get nightly scenarios green again, see #6134 
- [x] Get 10 more ETH nodes, see https://github.com/raiden-network/raiden/issues/6133
- [x] Get higher gas estimates for mainnet, see #6132
  - [x] Still need to deploy the RSB with the updated services https://github.com/raiden-network/team/issues/787
- [x] Provide a correct amount of DAI to testers

## The process is defined as follows
1. Check out https://github.com/karlb/scenario-player/tree/testing/mainnet-no-mint
2. Select correct raiden version. If you want to `develop`, then checkout the latest develop in the raiden repo, then install that **into the SP venv** and install the SP. E.g.
```
cd scenario-player && source venv/bin/activate
pip install -e ../raiden && make install-dev
```
3. If you want to use parity or infura (see spreadsheet) edit `evironment/mainnet.json` to select an eth node of your choice 

4. Check that you received an sufficient amount of ETH, DAI and RDN to run your 4 scenarios

5. Run scenario
```sh
python -m scenario_player run \
--keystore-file=$KEYFILE --password=$PASSWORD \
~/raiden/raiden/tests/scenarios/bf1_basic_functionality.yaml \
--environment environment/mainnet.json --no-ui
```

6. Update the spreadsheet with success / fail and the respective node logs, see https://docs.google.com/spreadsheets/d/1An2fZ1qZH9Cgq1bsFuLhpzl_y2OFpBAvuZZgYcJalxY/edit#gid=1869981213

7. When funds run low, wait for scenarios to finish, then reclaim with
```sh
python -m scenario_player reclaim-eth \
--keystore-file=$KEYFILE --password=$PASSWORD \
--min-age=0 --environment environment/mainnet.json \
--reclaim-token 0x6B175474E89094C44Da98b954EedeAC495271d0F --withdraw-from-udc
```

## Testers
@karlb @ulope @Dominik1999 @palango @hackaugusto @czepluch

**Comment by Dominik1999** [comment]
We had one issue with BF4 in the scenario mainnet testing session, see https://github.com/raiden-network/raiden/issues/6169

The issue is not a critical Raiden issue
