### ISSUE TITLE
Remove Internal Routing

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6496]
## Problems With Internal Routing
* Does not know about fee schedule. It currently always assumes 2% fees for the whole payment, which is expensive, but can still be too low in some cases
* Forces the client to build a representation of the whole network. This makes syncing the raiden client on mainnet at startup horrible slow (See https://github.com/raiden-network/raiden/issues/6209).
* Current implementation has several limitations. Better implemantations would duplicate more code from the PFS.
* Existing problems will only grow bigger with new features (e.g. better support for token swaps)
* Not tested in SP
* Not manually tested on Alderaan release

## Todos

Due to these problems, it is better to remove the internal routing and rely on the PFS for payments through non-direct channels.

- [x] Provide way to do non-direct payments in integration test without internal routing (give routes explicitly?)
- [x] Remove usage of internal routing from tests (delete test that are only about testing the internal routing)
- [ ] Remove internal routing from CLI flags and documentation
- [ ] Remove internal routing code

## Followups

- More selective filters during startup https://github.com/raiden-network/raiden/issues/6497
