### ISSUE TITLE
Faster syncing during startup by more selective filtering

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6497]
# Summary

Raiden can take a long time to start up on mainnet if it has not been been synced recently. Once the internal routing is removed (https://github.com/raiden-network/raiden/issues/6496), we need much fewer events than before. Using more selective filters should speed up the sync a lot.

# Todos

- [x] Find out which events we actually need to know about after startup
- [x] Use selective filtering during startup
- [x] Decide: should we change anything about filtering during runtime?
- [x] Do a simple before/after benchmark on mainnet (preferable with geth, parity and infura)

If the speedup is not sufficient, reconsider https://github.com/raiden-network/raiden/issues/6209.

# Additional Information

## Basic Filter Performance Test

Getting deposit events for a specific channel on our geth mainnet node for the last 100k block takes ~2s.

```
time curl -X POST http://geth.mainnet.ethnodes.brainbot.com:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address":["0x5b606943b36F3569E00EC4178A9f83eea8730184"], "fromBlock": "0xa265ee", "topics": ["0x2b55547a3b586ab51f65ee9ce4927fa6d25191388299988e89e059a02f9dd445", "0x0000000000000000000000000000000000000000000000000000000000000017"]}],"id":74}'

{"jsonrpc":"2.0","id":74,"result":[{"address":"0x5b606943b36f3569e00ec4178a9f83eea8730184","topics":["0x2b55547a3b586ab51f65ee9ce4927fa6d25191388299988e89e059a02f9dd445","0x0000000000000000000000000000000000000000000000000000000000000017","0x0000000000000000000000004e1ab8b6dc9f30e8e25eb3fa15b59ff7f26c53f3"],"data":"0x000000000000000000000000000000000000000000000000006a94d74f430000","blockNumber":"0xa28e05","transactionHash":"0xe8c6e745d4649997f7ecb6fac369d6ecc3410bb2a3a80437d27757079bca2dbe","transactionIndex":"0x73","blockHash":"0x3fdfd88c0062f694df5c26ff523f84905487ab6d766f5d401131bd0389f013f3","logIndex":"0x91","removed":false}]}

real    0m2.353s
```

## Light Client

@andrevmatos mentioned that the light client uses a similar approach. Talk to him when problems arise that might already be solved in the light client!

One of his comments regarding filtering for ChannelOpened events:

> You need 2 different requests: one for when you’re the first participant, and one for when you’re the second; you may do this only on the historic fetch though, and then on “live” filter, switch to a more permissive catch-all filter, and then filter client-side. We did it by first fetching open channels where we’re the first participants, then second, then fetch all other events for the channelIds we fetched first, sorted/interleaved these events and then switched to the catch-all live filter (a single filter for both open and other events)

### TokenNetworkRegistry

* TokenNetworkCreated

### TokenNetwork

Channel state changes

* ChannelOpened
* ChannelClosed
* ChannelSettled

Channel deposit changes

* ChannelNewDeposit
* ChannelWithdraw

Informational only:

* ChannelUnlocked
* NonClosingBalanceProofUpdated

### SecretRegistry

* SecretRevealed

**Comment by christianbrb** [comment]
@karlb Maybe you want to take a look at the Light Client code or talk with @andrevmatos. He has applied much stricter filtering already.

**Comment by andrevmatos** [comment]
Here's the code for our initial channels sync, if of any interest for reference.
https://github.com/raiden-network/light-client/blob/4b073d370c5d118c32b6d3ccea8ab518cab799d3/raiden-ts/src/channels/epics.ts#L368-L481
The TokenNetwork event monitoring is a little before in the same file.
Right now, we do 3 requests per TokenNetwork on past events sync (on startup), and a single filter for live events (which is efficient when monitoring multiple tokenNetworks). We've seen web3 allows also multiple contracts addresses on a single filter, so we are also considering monitoring all tokenNetworks with a single filter (array of addresses on the `address` field of the filter).
