### ISSUE TITLE
Implement (internal) cross token route format

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6512]
Sub-issue for https://github.com/raiden-network/raiden/issues/6506

## Description

For cross token payments the routing information will define a mediator which is expected to do the token swap. For this to happen we need to extend to current routing information with the token network address of each used channel.

## Tasks

- [ ] Define data format
- [ ] Decide if we have continue to support the old format or can make the new one backwards compatible
- [ ] Implement new format
  - [ ] Adapt `RouteState` and `HopState`
