### ISSUE TITLE
Add scenarios for cross token payments

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6519]
Sub-issue for https://github.com/raiden-network/raiden/issues/6506

## Description

While each sub-feature of cross token payments should have unit/integration tests, we also need to test the whole system at the SP level.

## Tasks

- [ ] Adapt SP payment task to new API
- [ ] Create scenarios for cross token payments
- [ ] Integrate the scenarios into the nightly runs

**Comment by ulope** [comment]
Ideally this would be natively supported in the SP by making it possible to deploy multiple tokens / token networks.
