### ISSUE TITLE
Repo Issue Responsibility

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6607]
We have several repos related to the Raiden project. For each of those, we should have one person who takes responsibility to keep the repo in an acceptable stake:

- Keep number of outdated issue and duplicates low
- Keep CI working
- Make sure urgent issues get prioritized

The responsible persons do not have to do the tasks themselves, but they must make sure that they get done.

Repos:
- [x] https://github.com/raiden-network/raiden @konradkonrad 
- [x] https://github.com/raiden-network/raiden-services @karlb
- [x] https://github.com/raiden-network/raiden-contracts @karlb
- [x] https://github.com/raiden-network/scenario-player @palango 
- [x] https://github.com/raiden-network/raiden-service-bundle @fredo 
- [x] https://github.com/raiden-network/scenarioplayer.ci.raiden.network @karlb 
- [x] https://github.com/raiden-network/spec @andrevmatos 

Only repos maintained by the Raiden core team are listed here.
