### ISSUE TITLE
webRTC: Reenable after toDevice message changes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6639]
In #6629 a new message path using `toDevice` messages was added. This causes some problems as the webRTC session initiation currently expects the communication to happen over matrix rooms.

### Tasks
- [ ] Make `invite`, `answer` and `hangup` messages use `toDevice` messages when enabled
- [ ] Handle receiving session initiation messages with `toDevice` messages
- [x] Reenable `test_web_rtc_message_sync`

**Comment by karlb** [comment]
Duplicate of https://github.com/raiden-network/raiden/issues/6701
