### ISSUE TITLE
Release v1.3

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6670]
The release includes faster syncing, making Raiden usage on the mainnet much more practical. WebRTC support for that release would be nice, but if it's not ready at release time, webRTC support will be disabled (even though it is in the codebase). The release will include all changes made to the develop branch at the time of this writing.

- [x] Choose release name: Bespin
- [x] Ensure new CM WebUI is used
  - [x] WebUI release (Planned for Dec 2nd)
  - [x] Update WebUI dependency (https://github.com/raiden-network/raiden/pull/6716)
  - [x] Include fix for case when PFS is not set? (https://github.com/raiden-network/webui/pull/581, https://github.com/raiden-network/raiden/pull/6717)
- [x] RSBs ready
  - [x] RSB release made (https://github.com/raiden-network/raiden-service-bundle/releases/tag/2020.11.2)
  - [x] ~~Deployed RSB version up to date (really necessary?)~~ 
  - [x] At least two RSB providers running which are not about to expire
  - [x] Update list of mainnet RSBs (https://github.com/raiden-network/raiden-service-bundle/pull/221)
- [x] Update docs (https://github.com/raiden-network/raiden/issues/6682)
- [x] Decide WebRTC in or out: out
- [x] Test db compatibility/upgradability (https://github.com/raiden-network/raiden/pull/6720)
- [x] Check changelog for missing entries (https://github.com/raiden-network/raiden/pull/6721)
- [x] Fixed secret registration gas cost bug (https://github.com/raiden-network/raiden/issues/6725)
- [x] testnet SP run done (existing errors accepted as known matrix issues)
- [x] Merge to master PR created
- [x] Merge PR reviewed
- [x] Get ETH for mainnet test
- [x] Clear up what's happening in https://github.com/raiden-network/raiden/issues/672
- [ ] mainnet SP run done
- [x] minimal manual mainnet testing
- [ ] Official OK for release
- [x] Merge gitbook drafts (and add missing links, see https://github.com/raiden-network/raiden/issues/6682)
- [ ] Released
- [ ] Update Wizard
- [ ] Release comms

**Comment by karlb** [comment]
Closed in favor of https://github.com/raiden-network/raiden/issues/6959
