### ISSUE TITLE
[Meta] Create a new (final) RC

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#7103]
# New RC today

# Critical Issues
- [x] Partial Withdraw Bug [#7093](https://github.com/raiden-network/raiden/issues/7093)
- [x] Error Handling Query Address Metadata [#7102](https://github.com/raiden-network/raiden/issues/7102)
- [x] Remove Refunds [#7082](https://github.com/raiden-network/raiden/pull/7082)
- [x] Deserialization issue on restart (`ContractSendChannelBatchUnlock`) [#7094](https://github.com/raiden-network/raiden/issues/7094) 

# Testnet Scenario Runs
*Depends on RC*
- [x] Prepare Goerli
- [x] Prepare Rinkeby (but could need more funds)

# Mainnet Testing with new RC
*Depends on RC*
- [x] manual Testing (Probably not complete test protocol)
- [x] Get a working Parity RPC
- [x] Scenario Runs
  - [x] MS1
  - [x] BF1

# Misc
- [x] In Script every 5th mediated payment gets stuck **Fernando**

# If nothing to do
- LC / PC Compatibility Generic Metadata (+ dont require pruned routes)
- Gas Price Strategy
    - ~Misleading Option `Dynamic`~
    - Revisit Gas Price Strategy
- RSB Problem (by Ulo)

**Comment by karlb** [comment]
This obviously refers to version 2 RC, while we are building RCs for version 3 now.
